/*
 * 站点管理
 * 站点管理第三方接口。 场景：对站点增删改查操作的第三方接口。
 *
 * OpenAPI spec version: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.huawei.cloudcampus.api.model.CreateSiteFail;
import com.huawei.cloudcampus.api.model.CreateSiteSuccess;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 创建站点返回模型。
 */
@ApiModel(description = "创建站点返回模型。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:19:01.736+08:00")
public class CreateSiteOut {
  @SerializedName("errcode")
  private String errcode = null;

  @SerializedName("errmsg")
  private String errmsg = null;

  @SerializedName("success")
  private List<CreateSiteSuccess> success = null;

  @SerializedName("fail")
  private List<CreateSiteFail> fail = null;

  public CreateSiteOut errcode(String errcode) {
    this.errcode = errcode;
    return this;
  }

   /**
   * 错误码。
   * return errcode
  **/
  @ApiModelProperty(value = "错误码。")
  public String getErrcode() {
    return errcode;
  }

   /**
   * 错误码。
   * Param errcode
  **/
  public void setErrcode(String errcode) {
    this.errcode = errcode;
  }

  public CreateSiteOut errmsg(String errmsg) {
    this.errmsg = errmsg;
    return this;
  }

   /**
   * 错误信息。
   * return errmsg
  **/
  @ApiModelProperty(value = "错误信息。")
  public String getErrmsg() {
    return errmsg;
  }

   /**
   * 错误信息。
   * Param errmsg
  **/
  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }

  public CreateSiteOut success(List<CreateSiteSuccess> success) {
    this.success = success;
    return this;
  }

  public CreateSiteOut addSuccessItem(CreateSiteSuccess successItem) {
    if (this.success == null) {
      this.success = new ArrayList<CreateSiteSuccess>();
    }
    this.success.add(successItem);
    return this;
  }

   /**
   * 创建成功的站点列表。
   * return success
  **/
  @ApiModelProperty(value = "创建成功的站点列表。")
  public List<CreateSiteSuccess> getSuccess() {
    return success;
  }

   /**
   * 创建成功的站点列表。
   * Param success
  **/
  public void setSuccess(List<CreateSiteSuccess> success) {
    this.success = success;
  }

  public CreateSiteOut fail(List<CreateSiteFail> fail) {
    this.fail = fail;
    return this;
  }

  public CreateSiteOut addFailItem(CreateSiteFail failItem) {
    if (this.fail == null) {
      this.fail = new ArrayList<CreateSiteFail>();
    }
    this.fail.add(failItem);
    return this;
  }

   /**
   * 创建失败的站点列表。
   * return fail
  **/
  @ApiModelProperty(value = "创建失败的站点列表。")
  public List<CreateSiteFail> getFail() {
    return fail;
  }

   /**
   * 创建失败的站点列表。
   * Param fail
  **/
  public void setFail(List<CreateSiteFail> fail) {
    this.fail = fail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSiteOut createSiteOut = (CreateSiteOut) o;
    return Objects.equals(this.errcode, createSiteOut.errcode) &&
        Objects.equals(this.errmsg, createSiteOut.errmsg) &&
        Objects.equals(this.success, createSiteOut.success) &&
        Objects.equals(this.fail, createSiteOut.fail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errcode, errmsg, success, fail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSiteOut {\n");
    
    sb.append("    errcode: ").append(toIndentedString(errcode)).append("\n");
    sb.append("    errmsg: ").append(toIndentedString(errmsg)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    fail: ").append(toIndentedString(fail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

