/*
 * 终端用户管理
 * 终端用户管理开放API。 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CutUserData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:26.055+08:00")
public class CutUserData {
  @SerializedName("message")
  private String message = null;

  @SerializedName("psessionid")
  private String psessionid = null;

  public CutUserData message(String message) {
    this.message = message;
    return this;
  }

   /**
   * 成功结果。
   * return message
  **/
  @ApiModelProperty(value = "成功结果。")
  public String getMessage() {
    return message;
  }

   /**
   * 成功结果。
   * Param message
  **/
  public void setMessage(String message) {
    this.message = message;
  }

  public CutUserData psessionid(String psessionid) {
    this.psessionid = psessionid;
    return this;
  }

   /**
   * 用户会话ID。
   * return psessionid
  **/
  @ApiModelProperty(value = "用户会话ID。")
  public String getPsessionid() {
    return psessionid;
  }

   /**
   * 用户会话ID。
   * Param psessionid
  **/
  public void setPsessionid(String psessionid) {
    this.psessionid = psessionid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CutUserData cutUserData = (CutUserData) o;
    return Objects.equals(this.message, cutUserData.message) &&
        Objects.equals(this.psessionid, cutUserData.psessionid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, psessionid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CutUserData {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    psessionid: ").append(toIndentedString(psessionid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

