/*
 * 配置结果查询
 * 查询配置结果
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 根据Example查询对象，暂时列出这些。
 */
@ApiModel(description = "根据Example查询对象，暂时列出这些。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:19:37.211+08:00")
public class FeatureItemStateDto {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("messageId")
  private String messageId = null;

  @SerializedName("operation")
  private Integer operation = null;

  @SerializedName("state")
  private Integer state = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  @SerializedName("updateTime")
  private String updateTime = null;

  public FeatureItemStateDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 单个特性ID。
   * return id
  **/
  @ApiModelProperty(value = "单个特性ID。")
  public String getId() {
    return id;
  }

   /**
   * 单个特性ID。
   * Param id
  **/
  public void setId(String id) {
    this.id = id;
  }

  public FeatureItemStateDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 单个特性名称。
   * return name
  **/
  @ApiModelProperty(value = "单个特性名称。")
  public String getName() {
    return name;
  }

   /**
   * 单个特性名称。
   * Param name
  **/
  public void setName(String name) {
    this.name = name;
  }

  public FeatureItemStateDto messageId(String messageId) {
    this.messageId = messageId;
    return this;
  }

   /**
   * 下发单个特性的报文ID。
   * return messageId
  **/
  @ApiModelProperty(value = "下发单个特性的报文ID。")
  public String getMessageId() {
    return messageId;
  }

   /**
   * 下发单个特性的报文ID。
   * Param messageId
  **/
  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }

  public FeatureItemStateDto operation(Integer operation) {
    this.operation = operation;
    return this;
  }

   /**
   * 单个特性对应的操作类型，取值范围：0---新增(Add)；1---删除(Delete)；2---修改(Update)。
   * return operation
  **/
  @ApiModelProperty(value = "单个特性对应的操作类型，取值范围：0---新增(Add)；1---删除(Delete)；2---修改(Update)。")
  public Integer getOperation() {
    return operation;
  }

   /**
   * 单个特性对应的操作类型，取值范围：0---新增(Add)；1---删除(Delete)；2---修改(Update)。
   * Param operation
  **/
  public void setOperation(Integer operation) {
    this.operation = operation;
  }

  public FeatureItemStateDto state(Integer state) {
    this.state = state;
    return this;
  }

   /**
   * 单个特性的配置下发状态，取值范围：0---成功；1---告警；2---预配置；3---失败；4---正在下发。
   * return state
  **/
  @ApiModelProperty(value = "单个特性的配置下发状态，取值范围：0---成功；1---告警；2---预配置；3---失败；4---正在下发。")
  public Integer getState() {
    return state;
  }

   /**
   * 单个特性的配置下发状态，取值范围：0---成功；1---告警；2---预配置；3---失败；4---正在下发。
   * Param state
  **/
  public void setState(Integer state) {
    this.state = state;
  }

  public FeatureItemStateDto errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * 错误信息。
   * return errorMessage
  **/
  @ApiModelProperty(value = "错误信息。")
  public String getErrorMessage() {
    return errorMessage;
  }

   /**
   * 错误信息。
   * Param errorMessage
  **/
  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public FeatureItemStateDto updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * 更新时间。
   * return updateTime
  **/
  @ApiModelProperty(value = "更新时间。")
  public String getUpdateTime() {
    return updateTime;
  }

   /**
   * 更新时间。
   * Param updateTime
  **/
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureItemStateDto featureItemStateDto = (FeatureItemStateDto) o;
    return Objects.equals(this.id, featureItemStateDto.id) &&
        Objects.equals(this.name, featureItemStateDto.name) &&
        Objects.equals(this.messageId, featureItemStateDto.messageId) &&
        Objects.equals(this.operation, featureItemStateDto.operation) &&
        Objects.equals(this.state, featureItemStateDto.state) &&
        Objects.equals(this.errorMessage, featureItemStateDto.errorMessage) &&
        Objects.equals(this.updateTime, featureItemStateDto.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, messageId, operation, state, errorMessage, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureItemStateDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

