/*
 * 设备升级
 * · 查询设备文件 · 创建站点升级 · 查询站点升级 · 查询设备升级 · 取消设备升级 · 删除站点升级 · 重新升级设备 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * 文件信息。
 */
@ApiModel(description = "文件信息。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:28.844+08:00")
public class FileInfoModel {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("fileName")
  private String fileName = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("depenedPkgVersion")
  private String depenedPkgVersion = null;

  public FileInfoModel id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 文件ID。
   * return id
  **/
  @ApiModelProperty(value = "文件ID。")
  public UUID getId() {
    return id;
  }

   /**
   * 文件ID。
   * Param id
  **/
  public void setId(UUID id) {
    this.id = id;
  }

  public FileInfoModel version(String version) {
    this.version = version;
    return this;
  }

   /**
   * 版本号。
   * return version
  **/
  @ApiModelProperty(value = "版本号。")
  public String getVersion() {
    return version;
  }

   /**
   * 版本号。
   * Param version
  **/
  public void setVersion(String version) {
    this.version = version;
  }

  public FileInfoModel fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * 文件名称。
   * return fileName
  **/
  @ApiModelProperty(value = "文件名称。")
  public String getFileName() {
    return fileName;
  }

   /**
   * 文件名称。
   * Param fileName
  **/
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public FileInfoModel displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * 文件别名。
   * return displayName
  **/
  @ApiModelProperty(value = "文件别名。")
  public String getDisplayName() {
    return displayName;
  }

   /**
   * 文件别名。
   * Param displayName
  **/
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public FileInfoModel depenedPkgVersion(String depenedPkgVersion) {
    this.depenedPkgVersion = depenedPkgVersion;
    return this;
  }

   /**
   * 如果是补丁，则为当前补丁依赖的大包版本号。
   * return depenedPkgVersion
  **/
  @ApiModelProperty(value = "如果是补丁，则为当前补丁依赖的大包版本号。")
  public String getDepenedPkgVersion() {
    return depenedPkgVersion;
  }

   /**
   * 如果是补丁，则为当前补丁依赖的大包版本号。
   * Param depenedPkgVersion
  **/
  public void setDepenedPkgVersion(String depenedPkgVersion) {
    this.depenedPkgVersion = depenedPkgVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileInfoModel fileInfoModel = (FileInfoModel) o;
    return Objects.equals(this.id, fileInfoModel.id) &&
        Objects.equals(this.version, fileInfoModel.version) &&
        Objects.equals(this.fileName, fileInfoModel.fileName) &&
        Objects.equals(this.displayName, fileInfoModel.displayName) &&
        Objects.equals(this.depenedPkgVersion, fileInfoModel.depenedPkgVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, version, fileName, displayName, depenedPkgVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileInfoModel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    depenedPkgVersion: ").append(toIndentedString(depenedPkgVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

