/*
 * 防火墙设备静态路由配置
 * 防火墙设备静态路由配置第三方接口。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.huawei.cloudcampus.api.model.DeviceFwStaticRouteInfoDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * FwStaticRouteInfoDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:36.994+08:00")
public class FwStaticRouteInfoDto {
  @SerializedName("pageIndex")
  private Integer pageIndex = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("totalRecords")
  private Integer totalRecords = null;

  @SerializedName("deviceFwStaticRoutePolicys")
  private List<DeviceFwStaticRouteInfoDto> deviceFwStaticRoutePolicys = null;

  public FwStaticRouteInfoDto pageIndex(Integer pageIndex) {
    this.pageIndex = pageIndex;
    return this;
  }

   /**
   * 页面索引。
   * minimum: 1
   * maximum: 65535
   * return pageIndex
  **/
  @ApiModelProperty(value = "页面索引。")
  public Integer getPageIndex() {
    return pageIndex;
  }

   /**
   * 页面索引。
   * minimum: 1
   * maximum: 65535
   * Param pageIndex
  **/
  public void setPageIndex(Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public FwStaticRouteInfoDto pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * 每页显示记录数。
   * minimum: 1
   * maximum: 1000
   * return pageSize
  **/
  @ApiModelProperty(value = "每页显示记录数。")
  public Integer getPageSize() {
    return pageSize;
  }

   /**
   * 每页显示记录数。
   * minimum: 1
   * maximum: 1000
   * Param pageSize
  **/
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public FwStaticRouteInfoDto totalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
    return this;
  }

   /**
   * 总记录数。
   * minimum: 1
   * maximum: 65535
   * return totalRecords
  **/
  @ApiModelProperty(value = "总记录数。")
  public Integer getTotalRecords() {
    return totalRecords;
  }

   /**
   * 总记录数。
   * minimum: 1
   * maximum: 65535
   * Param totalRecords
  **/
  public void setTotalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
  }

  public FwStaticRouteInfoDto deviceFwStaticRoutePolicys(List<DeviceFwStaticRouteInfoDto> deviceFwStaticRoutePolicys) {
    this.deviceFwStaticRoutePolicys = deviceFwStaticRoutePolicys;
    return this;
  }

  public FwStaticRouteInfoDto addDeviceFwStaticRoutePolicysItem(DeviceFwStaticRouteInfoDto deviceFwStaticRoutePolicysItem) {
    if (this.deviceFwStaticRoutePolicys == null) {
      this.deviceFwStaticRoutePolicys = new ArrayList<DeviceFwStaticRouteInfoDto>();
    }
    this.deviceFwStaticRoutePolicys.add(deviceFwStaticRoutePolicysItem);
    return this;
  }

   /**
   * 防火墙设备静态路由配置信息。
   * return deviceFwStaticRoutePolicys
  **/
  @ApiModelProperty(value = "防火墙设备静态路由配置信息。")
  public List<DeviceFwStaticRouteInfoDto> getDeviceFwStaticRoutePolicys() {
    return deviceFwStaticRoutePolicys;
  }

   /**
   * 防火墙设备静态路由配置信息。
   * Param deviceFwStaticRoutePolicys
  **/
  public void setDeviceFwStaticRoutePolicys(List<DeviceFwStaticRouteInfoDto> deviceFwStaticRoutePolicys) {
    this.deviceFwStaticRoutePolicys = deviceFwStaticRoutePolicys;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FwStaticRouteInfoDto fwStaticRouteInfoDto = (FwStaticRouteInfoDto) o;
    return Objects.equals(this.pageIndex, fwStaticRouteInfoDto.pageIndex) &&
        Objects.equals(this.pageSize, fwStaticRouteInfoDto.pageSize) &&
        Objects.equals(this.totalRecords, fwStaticRouteInfoDto.totalRecords) &&
        Objects.equals(this.deviceFwStaticRoutePolicys, fwStaticRouteInfoDto.deviceFwStaticRoutePolicys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageIndex, pageSize, totalRecords, deviceFwStaticRoutePolicys);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FwStaticRouteInfoDto {\n");
    
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("    deviceFwStaticRoutePolicys: ").append(toIndentedString(deviceFwStaticRoutePolicys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

