/*
 * 设备基本信息管理
 * 设备相关操作接口。 场景：对设备增删改查操作的第三方接口。
 *
 * OpenAPI spec version: 1.6.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.huawei.cloudcampus.api.model.GetDeviceBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 设备信息返回结果。
 */
@ApiModel(description = "设备信息返回结果。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-10-12T17:12:59.914+08:00")
public class GetDeviceResponseBean {
  @SerializedName("errcode")
  private String errcode = null;

  @SerializedName("errmsg")
  private String errmsg = null;

  @SerializedName("pageIndex")
  private Integer pageIndex = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("totalRecords")
  private Integer totalRecords = null;

  @SerializedName("data")
  private List<GetDeviceBean> data = null;

  public GetDeviceResponseBean errcode(String errcode) {
    this.errcode = errcode;
    return this;
  }

   /**
   * 错误码：当没有错误时返回0。
   * return errcode
  **/
  @ApiModelProperty(value = "错误码：当没有错误时返回0。")
  public String getErrcode() {
    return errcode;
  }

   /**
   * 错误码：当没有错误时返回0。
   * Param errcode
  **/
  public void setErrcode(String errcode) {
    this.errcode = errcode;
  }

  public GetDeviceResponseBean errmsg(String errmsg) {
    this.errmsg = errmsg;
    return this;
  }

   /**
   * 接口调用结果的描述信息。
   * return errmsg
  **/
  @ApiModelProperty(value = "接口调用结果的描述信息。")
  public String getErrmsg() {
    return errmsg;
  }

   /**
   * 接口调用结果的描述信息。
   * Param errmsg
  **/
  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }

  public GetDeviceResponseBean pageIndex(Integer pageIndex) {
    this.pageIndex = pageIndex;
    return this;
  }

   /**
   * 分页的序号。
   * return pageIndex
  **/
  @ApiModelProperty(value = "分页的序号。")
  public Integer getPageIndex() {
    return pageIndex;
  }

   /**
   * 分页的序号。
   * Param pageIndex
  **/
  public void setPageIndex(Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public GetDeviceResponseBean pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * 分页的大小。
   * return pageSize
  **/
  @ApiModelProperty(value = "分页的大小。")
  public Integer getPageSize() {
    return pageSize;
  }

   /**
   * 分页的大小。
   * Param pageSize
  **/
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public GetDeviceResponseBean totalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
    return this;
  }

   /**
   * 本次查询的设备总数。
   * return totalRecords
  **/
  @ApiModelProperty(value = "本次查询的设备总数。")
  public Integer getTotalRecords() {
    return totalRecords;
  }

   /**
   * 本次查询的设备总数。
   * Param totalRecords
  **/
  public void setTotalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
  }

  public GetDeviceResponseBean data(List<GetDeviceBean> data) {
    this.data = data;
    return this;
  }

  public GetDeviceResponseBean addDataItem(GetDeviceBean dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<GetDeviceBean>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * 查询的站点信息类。
   * return data
  **/
  @ApiModelProperty(value = "查询的站点信息类。")
  public List<GetDeviceBean> getData() {
    return data;
  }

   /**
   * 查询的站点信息类。
   * Param data
  **/
  public void setData(List<GetDeviceBean> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDeviceResponseBean getDeviceResponseBean = (GetDeviceResponseBean) o;
    return Objects.equals(this.errcode, getDeviceResponseBean.errcode) &&
        Objects.equals(this.errmsg, getDeviceResponseBean.errmsg) &&
        Objects.equals(this.pageIndex, getDeviceResponseBean.pageIndex) &&
        Objects.equals(this.pageSize, getDeviceResponseBean.pageSize) &&
        Objects.equals(this.totalRecords, getDeviceResponseBean.totalRecords) &&
        Objects.equals(this.data, getDeviceResponseBean.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errcode, errmsg, pageIndex, pageSize, totalRecords, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDeviceResponseBean {\n");
    
    sb.append("    errcode: ").append(toIndentedString(errcode)).append("\n");
    sb.append("    errmsg: ").append(toIndentedString(errmsg)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

