/*
 * License管理
 * 公有云license管理接口。 场景：对租户license操作的第三方接口。 
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.huawei.cloudcampus.api.model.ImportActiveCodeOutData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 导入激活码返回模型。
 */
@ApiModel(description = "导入激活码返回模型。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:42.233+08:00")
public class ImportActiveCodeOut {
  @SerializedName("errcode")
  private String errcode = null;

  @SerializedName("errmsg")
  private String errmsg = null;

  @SerializedName("data")
  private List<ImportActiveCodeOutData> data = null;

  public ImportActiveCodeOut errcode(String errcode) {
    this.errcode = errcode;
    return this;
  }

   /**
   * 错误码。
   * return errcode
  **/
  @ApiModelProperty(value = "错误码。")
  public String getErrcode() {
    return errcode;
  }

   /**
   * 错误码。
   * Param errcode
  **/
  public void setErrcode(String errcode) {
    this.errcode = errcode;
  }

  public ImportActiveCodeOut errmsg(String errmsg) {
    this.errmsg = errmsg;
    return this;
  }

   /**
   * 错误信息。
   * return errmsg
  **/
  @ApiModelProperty(value = "错误信息。")
  public String getErrmsg() {
    return errmsg;
  }

   /**
   * 错误信息。
   * Param errmsg
  **/
  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }

  public ImportActiveCodeOut data(List<ImportActiveCodeOutData> data) {
    this.data = data;
    return this;
  }

  public ImportActiveCodeOut addDataItem(ImportActiveCodeOutData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<ImportActiveCodeOutData>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * 激活码导入结果列表。
   * return data
  **/
  @ApiModelProperty(value = "激活码导入结果列表。")
  public List<ImportActiveCodeOutData> getData() {
    return data;
  }

   /**
   * 激活码导入结果列表。
   * Param data
  **/
  public void setData(List<ImportActiveCodeOutData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportActiveCodeOut importActiveCodeOut = (ImportActiveCodeOut) o;
    return Objects.equals(this.errcode, importActiveCodeOut.errcode) &&
        Objects.equals(this.errmsg, importActiveCodeOut.errmsg) &&
        Objects.equals(this.data, importActiveCodeOut.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errcode, errmsg, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportActiveCodeOut {\n");
    
    sb.append("    errcode: ").append(toIndentedString(errcode)).append("\n");
    sb.append("    errmsg: ").append(toIndentedString(errmsg)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

