/*
 * AP DHCP配置
 * AP DHCP配置第三方接口说明。 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 静态绑定。
 */
@ApiModel(description = "静态绑定。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:12.026+08:00")
public class IpBindingMacConfigApiDto {
  @SerializedName("staticIpAddress")
  private String staticIpAddress = null;

  @SerializedName("staticMacAddress")
  private String staticMacAddress = null;

  public IpBindingMacConfigApiDto staticIpAddress(String staticIpAddress) {
    this.staticIpAddress = staticIpAddress;
    return this;
  }

   /**
   * IP地址，不能与列表中其他IP重复。IP为上面网段（IP+mask计算得出）中的可分配IP地址，且不能为网关IP（上面配置IP）。
   * return staticIpAddress
  **/
  @ApiModelProperty(required = true, value = "IP地址，不能与列表中其他IP重复。IP为上面网段（IP+mask计算得出）中的可分配IP地址，且不能为网关IP（上面配置IP）。")
  public String getStaticIpAddress() {
    return staticIpAddress;
  }

   /**
   * IP地址，不能与列表中其他IP重复。IP为上面网段（IP+mask计算得出）中的可分配IP地址，且不能为网关IP（上面配置IP）。
   * Param staticIpAddress
  **/
  public void setStaticIpAddress(String staticIpAddress) {
    this.staticIpAddress = staticIpAddress;
  }

  public IpBindingMacConfigApiDto staticMacAddress(String staticMacAddress) {
    this.staticMacAddress = staticMacAddress;
    return this;
  }

   /**
   * MAC地址，不能与列表中其他MAC地址重复。MAC不能为广播（全F），组播（第一段2进制表示以“1”结尾）。
   * return staticMacAddress
  **/
  @ApiModelProperty(required = true, value = "MAC地址，不能与列表中其他MAC地址重复。MAC不能为广播（全F），组播（第一段2进制表示以“1”结尾）。")
  public String getStaticMacAddress() {
    return staticMacAddress;
  }

   /**
   * MAC地址，不能与列表中其他MAC地址重复。MAC不能为广播（全F），组播（第一段2进制表示以“1”结尾）。
   * Param staticMacAddress
  **/
  public void setStaticMacAddress(String staticMacAddress) {
    this.staticMacAddress = staticMacAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpBindingMacConfigApiDto ipBindingMacConfigApiDto = (IpBindingMacConfigApiDto) o;
    return Objects.equals(this.staticIpAddress, ipBindingMacConfigApiDto.staticIpAddress) &&
        Objects.equals(this.staticMacAddress, ipBindingMacConfigApiDto.staticMacAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(staticIpAddress, staticMacAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpBindingMacConfigApiDto {\n");
    
    sb.append("    staticIpAddress: ").append(toIndentedString(staticIpAddress)).append("\n");
    sb.append("    staticMacAddress: ").append(toIndentedString(staticMacAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

