/*
 * 交换机有线认证模板配置
 * 交换机有线认证模板，主要包括： · 创建站点下交换机有线认证模板配置 · 查询站点下交换机有线认证模板配置 · 修改站点下交换机有线认证模板配置 · 删除站点下交换机有线认证模板配置 · 修改站点交换机有线认证部分模板配置 · 增量绑站点交换机有线认证模板配置定 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.huawei.cloudcampus.api.model.LswAuthConfigProfileCore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LswAuthConfigProfile
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:43.536+08:00")
public class LswAuthConfigProfile {
  @SerializedName("authTemplateId")
  private String authTemplateId = null;

  @SerializedName("lswAuthConfigProfileCore")
  private LswAuthConfigProfileCore lswAuthConfigProfileCore = null;

  public LswAuthConfigProfile authTemplateId(String authTemplateId) {
    this.authTemplateId = authTemplateId;
    return this;
  }

   /**
   * 认证模板ID，UUID格式。
   * return authTemplateId
  **/
  @ApiModelProperty(required = true, value = "认证模板ID，UUID格式。")
  public String getAuthTemplateId() {
    return authTemplateId;
  }

   /**
   * 认证模板ID，UUID格式。
   * Param authTemplateId
  **/
  public void setAuthTemplateId(String authTemplateId) {
    this.authTemplateId = authTemplateId;
  }

  public LswAuthConfigProfile lswAuthConfigProfileCore(LswAuthConfigProfileCore lswAuthConfigProfileCore) {
    this.lswAuthConfigProfileCore = lswAuthConfigProfileCore;
    return this;
  }

   /**
   * Get lswAuthConfigProfileCore
   * return lswAuthConfigProfileCore
  **/
  @ApiModelProperty(required = true, value = "")
  public LswAuthConfigProfileCore getLswAuthConfigProfileCore() {
    return lswAuthConfigProfileCore;
  }

   /**
   * Set lswAuthConfigProfileCore
   * Param lswAuthConfigProfileCore
  **/
  public void setLswAuthConfigProfileCore(LswAuthConfigProfileCore lswAuthConfigProfileCore) {
    this.lswAuthConfigProfileCore = lswAuthConfigProfileCore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LswAuthConfigProfile lswAuthConfigProfile = (LswAuthConfigProfile) o;
    return Objects.equals(this.authTemplateId, lswAuthConfigProfile.authTemplateId) &&
        Objects.equals(this.lswAuthConfigProfileCore, lswAuthConfigProfile.lswAuthConfigProfileCore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authTemplateId, lswAuthConfigProfileCore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LswAuthConfigProfile {\n");
    
    sb.append("    authTemplateId: ").append(toIndentedString(authTemplateId)).append("\n");
    sb.append("    lswAuthConfigProfileCore: ").append(toIndentedString(lswAuthConfigProfileCore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

