/*
 * CIS服务接口
 * CIS操作接口说明： 1、创建CIS隔离 2、创建CIS阻断 3、撤销CIS阻断/隔离 4、阻断隔离应用状态查询 5、CIS策略命中率查询 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 命中率模型。
 */
@ApiModel(description = "命中率模型。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:17:59.469+08:00")
public class PolicyHitsListBuilder {
  @SerializedName("blockId")
  private String blockId = null;

  @SerializedName("deviceIp")
  private String deviceIp = null;

  @SerializedName("deviceName")
  private String deviceName = null;

  @SerializedName("hitsNumber")
  private Integer hitsNumber = null;

  @SerializedName("policyName")
  private String policyName = null;

  public PolicyHitsListBuilder blockId(String blockId) {
    this.blockId = blockId;
    return this;
  }

   /**
   * 事件ID，UUID格式。
   * return blockId
  **/
  @ApiModelProperty(value = "事件ID，UUID格式。")
  public String getBlockId() {
    return blockId;
  }

   /**
   * 事件ID，UUID格式。
   * Param blockId
  **/
  public void setBlockId(String blockId) {
    this.blockId = blockId;
  }

  public PolicyHitsListBuilder deviceIp(String deviceIp) {
    this.deviceIp = deviceIp;
    return this;
  }

   /**
   * 设备IP，此字段只存在campus融合场景，只支持IPV4格式。
   * return deviceIp
  **/
  @ApiModelProperty(value = "设备IP，此字段只存在campus融合场景，只支持IPV4格式。")
  public String getDeviceIp() {
    return deviceIp;
  }

   /**
   * 设备IP，此字段只存在campus融合场景，只支持IPV4格式。
   * Param deviceIp
  **/
  public void setDeviceIp(String deviceIp) {
    this.deviceIp = deviceIp;
  }

  public PolicyHitsListBuilder deviceName(String deviceName) {
    this.deviceName = deviceName;
    return this;
  }

   /**
   * 设备名称，此字段只存在campus融合场景。
   * return deviceName
  **/
  @ApiModelProperty(value = "设备名称，此字段只存在campus融合场景。")
  public String getDeviceName() {
    return deviceName;
  }

   /**
   * 设备名称，此字段只存在campus融合场景。
   * Param deviceName
  **/
  public void setDeviceName(String deviceName) {
    this.deviceName = deviceName;
  }

  public PolicyHitsListBuilder hitsNumber(Integer hitsNumber) {
    this.hitsNumber = hitsNumber;
    return this;
  }

   /**
   * 命中次数。
   * return hitsNumber
  **/
  @ApiModelProperty(value = "命中次数。")
  public Integer getHitsNumber() {
    return hitsNumber;
  }

   /**
   * 命中次数。
   * Param hitsNumber
  **/
  public void setHitsNumber(Integer hitsNumber) {
    this.hitsNumber = hitsNumber;
  }

  public PolicyHitsListBuilder policyName(String policyName) {
    this.policyName = policyName;
    return this;
  }

   /**
   * 策略名称。
   * return policyName
  **/
  @ApiModelProperty(value = "策略名称。")
  public String getPolicyName() {
    return policyName;
  }

   /**
   * 策略名称。
   * Param policyName
  **/
  public void setPolicyName(String policyName) {
    this.policyName = policyName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyHitsListBuilder policyHitsListBuilder = (PolicyHitsListBuilder) o;
    return Objects.equals(this.blockId, policyHitsListBuilder.blockId) &&
        Objects.equals(this.deviceIp, policyHitsListBuilder.deviceIp) &&
        Objects.equals(this.deviceName, policyHitsListBuilder.deviceName) &&
        Objects.equals(this.hitsNumber, policyHitsListBuilder.hitsNumber) &&
        Objects.equals(this.policyName, policyHitsListBuilder.policyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockId, deviceIp, deviceName, hitsNumber, policyName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyHitsListBuilder {\n");
    
    sb.append("    blockId: ").append(toIndentedString(blockId)).append("\n");
    sb.append("    deviceIp: ").append(toIndentedString(deviceIp)).append("\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    hitsNumber: ").append(toIndentedString(hitsNumber)).append("\n");
    sb.append("    policyName: ").append(toIndentedString(policyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

