/*
 * AP网口IOT插卡管理
 * AP网口IOT插卡查询及操作接口。 场景：对AP网口IOT插卡查询及操作的第三方接口。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.huawei.cloudcampus.api.model.IotCmdResultInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 查询AP IOT命令下发的状态出参.
 */
@ApiModel(description = "查询AP IOT命令下发的状态出参.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:14.620+08:00")
public class QueryCmdResultOut {
  @SerializedName("errcode")
  private String errcode = null;

  @SerializedName("errmsg")
  private String errmsg = null;

  @SerializedName("pageIndex")
  private Integer pageIndex = null;

  @SerializedName("pageSize")
  private Integer pageSize = null;

  @SerializedName("totalRecords")
  private Integer totalRecords = null;

  @SerializedName("data")
  private List<IotCmdResultInfo> data = new ArrayList<IotCmdResultInfo>();

  public QueryCmdResultOut errcode(String errcode) {
    this.errcode = errcode;
    return this;
  }

   /**
   * 错误码。
   * return errcode
  **/
  @ApiModelProperty(required = true, value = "错误码。")
  public String getErrcode() {
    return errcode;
  }

   /**
   * 错误码。
   * Param errcode
  **/
  public void setErrcode(String errcode) {
    this.errcode = errcode;
  }

  public QueryCmdResultOut errmsg(String errmsg) {
    this.errmsg = errmsg;
    return this;
  }

   /**
   * 错误信息。
   * return errmsg
  **/
  @ApiModelProperty(required = true, value = "错误信息。")
  public String getErrmsg() {
    return errmsg;
  }

   /**
   * 错误信息。
   * Param errmsg
  **/
  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }

  public QueryCmdResultOut pageIndex(Integer pageIndex) {
    this.pageIndex = pageIndex;
    return this;
  }

   /**
   * 分页的序号。
   * minimum: 1
   * return pageIndex
  **/
  @ApiModelProperty(value = "分页的序号。")
  public Integer getPageIndex() {
    return pageIndex;
  }

   /**
   * 分页的序号。
   * minimum: 1
   * Param pageIndex
  **/
  public void setPageIndex(Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public QueryCmdResultOut pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * 分页大小。
   * return pageSize
  **/
  @ApiModelProperty(value = "分页大小。")
  public Integer getPageSize() {
    return pageSize;
  }

   /**
   * 分页大小。
   * Param pageSize
  **/
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public QueryCmdResultOut totalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
    return this;
  }

   /**
   * 总数量。
   * minimum: 0
   * return totalRecords
  **/
  @ApiModelProperty(value = "总数量。")
  public Integer getTotalRecords() {
    return totalRecords;
  }

   /**
   * 总数量。
   * minimum: 0
   * Param totalRecords
  **/
  public void setTotalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
  }

  public QueryCmdResultOut data(List<IotCmdResultInfo> data) {
    this.data = data;
    return this;
  }

  public QueryCmdResultOut addDataItem(IotCmdResultInfo dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * AP IOT命令下发结果信息。
   * return data
  **/
  @ApiModelProperty(required = true, value = "AP IOT命令下发结果信息。")
  public List<IotCmdResultInfo> getData() {
    return data;
  }

   /**
   * AP IOT命令下发结果信息。
   * Param data
  **/
  public void setData(List<IotCmdResultInfo> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryCmdResultOut queryCmdResultOut = (QueryCmdResultOut) o;
    return Objects.equals(this.errcode, queryCmdResultOut.errcode) &&
        Objects.equals(this.errmsg, queryCmdResultOut.errmsg) &&
        Objects.equals(this.pageIndex, queryCmdResultOut.pageIndex) &&
        Objects.equals(this.pageSize, queryCmdResultOut.pageSize) &&
        Objects.equals(this.totalRecords, queryCmdResultOut.totalRecords) &&
        Objects.equals(this.data, queryCmdResultOut.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errcode, errmsg, pageIndex, pageSize, totalRecords, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryCmdResultOut {\n");
    
    sb.append("    errcode: ").append(toIndentedString(errcode)).append("\n");
    sb.append("    errmsg: ").append(toIndentedString(errmsg)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

