/*
 * RADIUS模板管理
 * RADIUS模板配置第三方北向接口说明。 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 备认证服务器。创建时，如果配置备认证服务器，IP地址和端口必须同时配置。
 */
@ApiModel(description = "备认证服务器。创建时，如果配置备认证服务器，IP地址和端口必须同时配置。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:57.602+08:00")
public class RadiusTempDtoSlaveAuthServer {
  @SerializedName("serverAddress")
  private String serverAddress = null;

  @SerializedName("port")
  private Integer port = null;

  public RadiusTempDtoSlaveAuthServer serverAddress(String serverAddress) {
    this.serverAddress = serverAddress;
    return this;
  }

   /**
   * 服务器IP地址。PUT操作时，如果备认证服务器中该字段设置为空字符串\&quot;\&quot;，则将备认证服务器设置为空。
   * return serverAddress
  **/
  @ApiModelProperty(value = "服务器IP地址。PUT操作时，如果备认证服务器中该字段设置为空字符串\"\"，则将备认证服务器设置为空。")
  public String getServerAddress() {
    return serverAddress;
  }

   /**
   * 服务器IP地址。PUT操作时，如果备认证服务器中该字段设置为空字符串\&quot;\&quot;，则将备认证服务器设置为空。
   * Param serverAddress
  **/
  public void setServerAddress(String serverAddress) {
    this.serverAddress = serverAddress;
  }

  public RadiusTempDtoSlaveAuthServer port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * 服务器端口。
   * minimum: 1
   * maximum: 65535
   * return port
  **/
  @ApiModelProperty(value = "服务器端口。")
  public Integer getPort() {
    return port;
  }

   /**
   * 服务器端口。
   * minimum: 1
   * maximum: 65535
   * Param port
  **/
  public void setPort(Integer port) {
    this.port = port;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RadiusTempDtoSlaveAuthServer radiusTempDtoSlaveAuthServer = (RadiusTempDtoSlaveAuthServer) o;
    return Objects.equals(this.serverAddress, radiusTempDtoSlaveAuthServer.serverAddress) &&
        Objects.equals(this.port, radiusTempDtoSlaveAuthServer.port);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serverAddress, port);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RadiusTempDtoSlaveAuthServer {\n");
    
    sb.append("    serverAddress: ").append(toIndentedString(serverAddress)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

