/*
 * 设备出厂设置恢复
 * 设备恢复出厂设置第三方接口。
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * 恢复出厂设置失败的设备信息及失败原因。
 */
@ApiModel(description = "恢复出厂设置失败的设备信息及失败原因。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:19:00.439+08:00")
public class ResetDeviceFailedDto {
  @SerializedName("deviceId")
  private UUID deviceId = null;

  @SerializedName("esn")
  private String esn = null;

  @SerializedName("errmsg")
  private String errmsg = null;

  @SerializedName("errcode")
  private String errcode = null;

  public ResetDeviceFailedDto deviceId(UUID deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * 设备ID。
   * return deviceId
  **/
  @ApiModelProperty(value = "设备ID。")
  public UUID getDeviceId() {
    return deviceId;
  }

   /**
   * 设备ID。
   * Param deviceId
  **/
  public void setDeviceId(UUID deviceId) {
    this.deviceId = deviceId;
  }

  public ResetDeviceFailedDto esn(String esn) {
    this.esn = esn;
    return this;
  }

   /**
   * 设备ESN号。
   * return esn
  **/
  @ApiModelProperty(value = "设备ESN号。")
  public String getEsn() {
    return esn;
  }

   /**
   * 设备ESN号。
   * Param esn
  **/
  public void setEsn(String esn) {
    this.esn = esn;
  }

  public ResetDeviceFailedDto errmsg(String errmsg) {
    this.errmsg = errmsg;
    return this;
  }

   /**
   * 设备恢复出厂设置失败错误信息。
   * return errmsg
  **/
  @ApiModelProperty(value = "设备恢复出厂设置失败错误信息。")
  public String getErrmsg() {
    return errmsg;
  }

   /**
   * 设备恢复出厂设置失败错误信息。
   * Param errmsg
  **/
  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }

  public ResetDeviceFailedDto errcode(String errcode) {
    this.errcode = errcode;
    return this;
  }

   /**
   * 设备恢复出厂设置失败错误码。
   * return errcode
  **/
  @ApiModelProperty(value = "设备恢复出厂设置失败错误码。")
  public String getErrcode() {
    return errcode;
  }

   /**
   * 设备恢复出厂设置失败错误码。
   * Param errcode
  **/
  public void setErrcode(String errcode) {
    this.errcode = errcode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResetDeviceFailedDto resetDeviceFailedDto = (ResetDeviceFailedDto) o;
    return Objects.equals(this.deviceId, resetDeviceFailedDto.deviceId) &&
        Objects.equals(this.esn, resetDeviceFailedDto.esn) &&
        Objects.equals(this.errmsg, resetDeviceFailedDto.errmsg) &&
        Objects.equals(this.errcode, resetDeviceFailedDto.errcode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, esn, errmsg, errcode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResetDeviceFailedDto {\n");
    
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    esn: ").append(toIndentedString(esn)).append("\n");
    sb.append("    errmsg: ").append(toIndentedString(errmsg)).append("\n");
    sb.append("    errcode: ").append(toIndentedString(errcode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

