/*
 * 站点模板管理
 * 站点模板第三方接口说明。 
 *
 * OpenAPI spec version: 1.2.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 站点模板信息。
 */
@ApiModel(description = "站点模板信息。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:19:09.284+08:00")
public class SiteTempResponseDto {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("types")
  private List<String> types = null;

  @SerializedName("custom")
  private Boolean custom = null;

  @SerializedName("configIdentifies")
  private String configIdentifies = null;

  public SiteTempResponseDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 站点模板ID，UUID格式。
   * return id
  **/
  @ApiModelProperty(value = "站点模板ID，UUID格式。")
  public String getId() {
    return id;
  }

   /**
   * 站点模板ID，UUID格式。
   * Param id
  **/
  public void setId(String id) {
    this.id = id;
  }

  public SiteTempResponseDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 站点模板名称。
   * return name
  **/
  @ApiModelProperty(value = "站点模板名称。")
  public String getName() {
    return name;
  }

   /**
   * 站点模板名称。
   * Param name
  **/
  public void setName(String name) {
    this.name = name;
  }

  public SiteTempResponseDto types(List<String> types) {
    this.types = types;
    return this;
  }

  public SiteTempResponseDto addTypesItem(String typesItem) {
    if (this.types == null) {
      this.types = new ArrayList<String>();
    }
    this.types.add(typesItem);
    return this;
  }

   /**
   * 站点模板类型列表。
   * return types
  **/
  @ApiModelProperty(value = "站点模板类型列表。")
  public List<String> getTypes() {
    return types;
  }

   /**
   * 站点模板类型列表。
   * Param types
  **/
  public void setTypes(List<String> types) {
    this.types = types;
  }

  public SiteTempResponseDto custom(Boolean custom) {
    this.custom = custom;
    return this;
  }

   /**
   * 是否定制特性。
   * return custom
  **/
  @ApiModelProperty(value = "是否定制特性。")
  public Boolean getCustom() {
    return custom;
  }

   /**
   * 是否定制特性。
   * Param custom
  **/
  public void setCustom(Boolean custom) {
    this.custom = custom;
  }

  public SiteTempResponseDto configIdentifies(String configIdentifies) {
    this.configIdentifies = configIdentifies;
    return this;
  }

   /**
   * 支持定制的特性集合，字符串格式，以，分隔
   * return configIdentifies
  **/
  @ApiModelProperty(value = "支持定制的特性集合，字符串格式，以，分隔")
  public String getConfigIdentifies() {
    return configIdentifies;
  }

   /**
   * 支持定制的特性集合，字符串格式，以，分隔
   * Param configIdentifies
  **/
  public void setConfigIdentifies(String configIdentifies) {
    this.configIdentifies = configIdentifies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SiteTempResponseDto siteTempResponseDto = (SiteTempResponseDto) o;
    return Objects.equals(this.id, siteTempResponseDto.id) &&
        Objects.equals(this.name, siteTempResponseDto.name) &&
        Objects.equals(this.types, siteTempResponseDto.types) &&
        Objects.equals(this.custom, siteTempResponseDto.custom) &&
        Objects.equals(this.configIdentifies, siteTempResponseDto.configIdentifies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, types, custom, configIdentifies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SiteTempResponseDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    configIdentifies: ").append(toIndentedString(configIdentifies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

