/*
 * AP SSID配置管理
 * AP SSID第三方接口。
 *
 * OpenAPI spec version: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.huawei.cloudcampus.api.model.AuthContentDto;
import com.huawei.cloudcampus.api.model.PolicyContentDto;
import com.huawei.cloudcampus.api.model.SsidConfigDto;
import com.huawei.cloudcampus.api.model.TagDto;
import com.huawei.cloudcampus.api.model.VlanDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SsidConfigOut
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:17.238+08:00")
public class SsidConfigOut {
  @SerializedName("name")
  private String name = null;

  @SerializedName("tags")
  private List<TagDto> tags = null;

  @SerializedName("enable")
  private Boolean enable = null;

  /**
   * 网络连接方式，大小写敏感，前后不能有空格，且不能含有全角字符。
   */
  @JsonAdapter(ConnectionModeEnum.Adapter.class)
  public enum ConnectionModeEnum {
    BRIDGE("bridge"),
    
    NAT("nat");

    private String value;

    ConnectionModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConnectionModeEnum fromValue(String text) {
      for (ConnectionModeEnum b : ConnectionModeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ConnectionModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConnectionModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConnectionModeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ConnectionModeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("connectionMode")
  private ConnectionModeEnum connectionMode = null;

  @SerializedName("vlans")
  private List<VlanDto> vlans = null;

  @SerializedName("hidedEnable")
  private Boolean hidedEnable = null;

  @SerializedName("relativeRadios")
  private Integer relativeRadios = null;

  @SerializedName("frequencyNavigation")
  private Boolean frequencyNavigation = null;

  @SerializedName("maxUserNumber")
  private Integer maxUserNumber = null;

  @SerializedName("userSeparation")
  private Boolean userSeparation = null;

  @SerializedName("ssidAuth")
  private AuthContentDto ssidAuth = null;

  @SerializedName("ssidPolicy")
  private PolicyContentDto ssidPolicy = null;

  @SerializedName("dot11r")
  private Boolean dot11r = null;

  @SerializedName("reassociateTimeout")
  private Integer reassociateTimeout = null;

  @SerializedName("id")
  private String id = null;

  public SsidConfigOut name(String name) {
    this.name = name;
    return this;
  }

   /**
   * SSID名称。长度为1~32字节（UTF-8编码），不能包含特殊符号&amp;、&#x3D;、？、#、%、+。当以空格开头或结尾时，最大长度减少2字节；当以\&quot;开头时，最大长度减少1字节。
   * return name
  **/
  @ApiModelProperty(required = true, value = "SSID名称。长度为1~32字节（UTF-8编码），不能包含特殊符号&、=、？、#、%、+。当以空格开头或结尾时，最大长度减少2字节；当以\"开头时，最大长度减少1字节。")
  public String getName() {
    return name;
  }

   /**
   * SSID名称。长度为1~32字节（UTF-8编码），不能包含特殊符号&amp;、&#x3D;、？、#、%、+。当以空格开头或结尾时，最大长度减少2字节；当以\&quot;开头时，最大长度减少1字节。
   * Param name
  **/
  public void setName(String name) {
    this.name = name;
  }

  public SsidConfigOut tags(List<TagDto> tags) {
    this.tags = tags;
    return this;
  }

  public SsidConfigOut addTagsItem(TagDto tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<TagDto>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * 设备标签列表，总数不能超过10个。如果指定标签列表，SSID会下发给带有列表中标签的设备。如果不指定，会下发给站点所有设备。
   * return tags
  **/
  @ApiModelProperty(value = "设备标签列表，总数不能超过10个。如果指定标签列表，SSID会下发给带有列表中标签的设备。如果不指定，会下发给站点所有设备。")
  public List<TagDto> getTags() {
    return tags;
  }

   /**
   * 设备标签列表，总数不能超过10个。如果指定标签列表，SSID会下发给带有列表中标签的设备。如果不指定，会下发给站点所有设备。
   * Param tags
  **/
  public void setTags(List<TagDto> tags) {
    this.tags = tags;
  }

  public SsidConfigOut enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * 工作状态开启。
   * return enable
  **/
  @ApiModelProperty(required = true, value = "工作状态开启。")
  public Boolean getEnable() {
    return enable;
  }

   /**
   * 工作状态开启。
   * Param enable
  **/
  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public SsidConfigOut connectionMode(ConnectionModeEnum connectionMode) {
    this.connectionMode = connectionMode;
    return this;
  }

   /**
   * 网络连接方式，大小写敏感，前后不能有空格，且不能含有全角字符。
   * return connectionMode
  **/
  @ApiModelProperty(required = true, value = "网络连接方式，大小写敏感，前后不能有空格，且不能含有全角字符。")
  public ConnectionModeEnum getConnectionMode() {
    return connectionMode;
  }

   /**
   * 网络连接方式，大小写敏感，前后不能有空格，且不能含有全角字符。
   * Param connectionMode
  **/
  public void setConnectionMode(ConnectionModeEnum connectionMode) {
    this.connectionMode = connectionMode;
  }

  public SsidConfigOut vlans(List<VlanDto> vlans) {
    this.vlans = vlans;
    return this;
  }

  public SsidConfigOut addVlansItem(VlanDto vlansItem) {
    if (this.vlans == null) {
      this.vlans = new ArrayList<VlanDto>();
    }
    this.vlans.add(vlansItem);
    return this;
  }

   /**
   * SSID所属的VLAN配置信息。当vlans参数为空时系统默认生成一条优先级为0的VLAN配置信息。
   * return vlans
  **/
  @ApiModelProperty(value = "SSID所属的VLAN配置信息。当vlans参数为空时系统默认生成一条优先级为0的VLAN配置信息。")
  public List<VlanDto> getVlans() {
    return vlans;
  }

   /**
   * SSID所属的VLAN配置信息。当vlans参数为空时系统默认生成一条优先级为0的VLAN配置信息。
   * Param vlans
  **/
  public void setVlans(List<VlanDto> vlans) {
    this.vlans = vlans;
  }

  public SsidConfigOut hidedEnable(Boolean hidedEnable) {
    this.hidedEnable = hidedEnable;
    return this;
  }

   /**
   * 是否隐藏SSID。
   * return hidedEnable
  **/
  @ApiModelProperty(required = true, value = "是否隐藏SSID。")
  public Boolean getHidedEnable() {
    return hidedEnable;
  }

   /**
   * 是否隐藏SSID。
   * Param hidedEnable
  **/
  public void setHidedEnable(Boolean hidedEnable) {
    this.hidedEnable = hidedEnable;
  }

  public SsidConfigOut relativeRadios(Integer relativeRadios) {
    this.relativeRadios = relativeRadios;
    return this;
  }

   /**
   * 射频类型。 1 --- 2.4G(wlan-radio 0/0/0)。 2 --- 5G(wlan-radio 0/0/1)。 3 --- 2.4G(wlan-radio 0/0/0)&amp;5G(wlan-radio 0/0/1)。 4 --- 5G(wlan-radio 0/0/2)。 5 --- 2.4G(wlan-radio 0/0/0)&amp;5G(wlan-radio 0/0/2)。 6 --- 5G(wlan-radio 0/0/1)&amp;5G(wlan-radio 0/0/2)。 7 --- 2.4G(wlan-radio 0/0/0)&amp;5G(wlan-radio 0/0/1)&amp;5G(wlan-radio 0/0/2)。
   * return relativeRadios
  **/
  @ApiModelProperty(required = true, value = "射频类型。 1 --- 2.4G(wlan-radio 0/0/0)。 2 --- 5G(wlan-radio 0/0/1)。 3 --- 2.4G(wlan-radio 0/0/0)&5G(wlan-radio 0/0/1)。 4 --- 5G(wlan-radio 0/0/2)。 5 --- 2.4G(wlan-radio 0/0/0)&5G(wlan-radio 0/0/2)。 6 --- 5G(wlan-radio 0/0/1)&5G(wlan-radio 0/0/2)。 7 --- 2.4G(wlan-radio 0/0/0)&5G(wlan-radio 0/0/1)&5G(wlan-radio 0/0/2)。")
  public Integer getRelativeRadios() {
    return relativeRadios;
  }

   /**
   * 射频类型。 1 --- 2.4G(wlan-radio 0/0/0)。 2 --- 5G(wlan-radio 0/0/1)。 3 --- 2.4G(wlan-radio 0/0/0)&amp;5G(wlan-radio 0/0/1)。 4 --- 5G(wlan-radio 0/0/2)。 5 --- 2.4G(wlan-radio 0/0/0)&amp;5G(wlan-radio 0/0/2)。 6 --- 5G(wlan-radio 0/0/1)&amp;5G(wlan-radio 0/0/2)。 7 --- 2.4G(wlan-radio 0/0/0)&amp;5G(wlan-radio 0/0/1)&amp;5G(wlan-radio 0/0/2)。
   * Param relativeRadios
  **/
  public void setRelativeRadios(Integer relativeRadios) {
    this.relativeRadios = relativeRadios;
  }

  public SsidConfigOut frequencyNavigation(Boolean frequencyNavigation) {
    this.frequencyNavigation = frequencyNavigation;
    return this;
  }

   /**
   * 是否开启频谱导航。
   * return frequencyNavigation
  **/
  @ApiModelProperty(value = "是否开启频谱导航。")
  public Boolean getFrequencyNavigation() {
    return frequencyNavigation;
  }

   /**
   * 是否开启频谱导航。
   * Param frequencyNavigation
  **/
  public void setFrequencyNavigation(Boolean frequencyNavigation) {
    this.frequencyNavigation = frequencyNavigation;
  }

  public SsidConfigOut maxUserNumber(Integer maxUserNumber) {
    this.maxUserNumber = maxUserNumber;
    return this;
  }

   /**
   * 最大用户数。
   * minimum: 1
   * maximum: 512
   * return maxUserNumber
  **/
  @ApiModelProperty(required = true, value = "最大用户数。")
  public Integer getMaxUserNumber() {
    return maxUserNumber;
  }

   /**
   * 最大用户数。
   * minimum: 1
   * maximum: 512
   * Param maxUserNumber
  **/
  public void setMaxUserNumber(Integer maxUserNumber) {
    this.maxUserNumber = maxUserNumber;
  }

  public SsidConfigOut userSeparation(Boolean userSeparation) {
    this.userSeparation = userSeparation;
    return this;
  }

   /**
   * 是否用户隔离。
   * return userSeparation
  **/
  @ApiModelProperty(required = true, value = "是否用户隔离。")
  public Boolean getUserSeparation() {
    return userSeparation;
  }

   /**
   * 是否用户隔离。
   * Param userSeparation
  **/
  public void setUserSeparation(Boolean userSeparation) {
    this.userSeparation = userSeparation;
  }

  public SsidConfigOut ssidAuth(AuthContentDto ssidAuth) {
    this.ssidAuth = ssidAuth;
    return this;
  }

   /**
   * Get ssidAuth
   * return ssidAuth
  **/
  @ApiModelProperty(required = true, value = "")
  public AuthContentDto getSsidAuth() {
    return ssidAuth;
  }

   /**
   * Set ssidAuth
   * Param ssidAuth
  **/
  public void setSsidAuth(AuthContentDto ssidAuth) {
    this.ssidAuth = ssidAuth;
  }

  public SsidConfigOut ssidPolicy(PolicyContentDto ssidPolicy) {
    this.ssidPolicy = ssidPolicy;
    return this;
  }

   /**
   * Get ssidPolicy
   * return ssidPolicy
  **/
  @ApiModelProperty(required = true, value = "")
  public PolicyContentDto getSsidPolicy() {
    return ssidPolicy;
  }

   /**
   * Set ssidPolicy
   * Param ssidPolicy
  **/
  public void setSsidPolicy(PolicyContentDto ssidPolicy) {
    this.ssidPolicy = ssidPolicy;
  }

  public SsidConfigOut dot11r(Boolean dot11r) {
    this.dot11r = dot11r;
    return this;
  }

   /**
   * 使能802.11r快速漫游功能。
   * return dot11r
  **/
  @ApiModelProperty(value = "使能802.11r快速漫游功能。")
  public Boolean getDot11r() {
    return dot11r;
  }

   /**
   * 使能802.11r快速漫游功能。
   * Param dot11r
  **/
  public void setDot11r(Boolean dot11r) {
    this.dot11r = dot11r;
  }

  public SsidConfigOut reassociateTimeout(Integer reassociateTimeout) {
    this.reassociateTimeout = reassociateTimeout;
    return this;
  }

   /**
   * 重新关联的超时时间，单位为秒。
   * minimum: 1
   * maximum: 10
   * return reassociateTimeout
  **/
  @ApiModelProperty(value = "重新关联的超时时间，单位为秒。")
  public Integer getReassociateTimeout() {
    return reassociateTimeout;
  }

   /**
   * 重新关联的超时时间，单位为秒。
   * minimum: 1
   * maximum: 10
   * Param reassociateTimeout
  **/
  public void setReassociateTimeout(Integer reassociateTimeout) {
    this.reassociateTimeout = reassociateTimeout;
  }

  public SsidConfigOut id(String id) {
    this.id = id;
    return this;
  }

   /**
   * SSID唯一标识。
   * return id
  **/
  @ApiModelProperty(value = "SSID唯一标识。")
  public String getId() {
    return id;
  }

   /**
   * SSID唯一标识。
   * Param id
  **/
  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SsidConfigOut ssidConfigOut = (SsidConfigOut) o;
    return Objects.equals(this.name, ssidConfigOut.name) &&
        Objects.equals(this.tags, ssidConfigOut.tags) &&
        Objects.equals(this.enable, ssidConfigOut.enable) &&
        Objects.equals(this.connectionMode, ssidConfigOut.connectionMode) &&
        Objects.equals(this.vlans, ssidConfigOut.vlans) &&
        Objects.equals(this.hidedEnable, ssidConfigOut.hidedEnable) &&
        Objects.equals(this.relativeRadios, ssidConfigOut.relativeRadios) &&
        Objects.equals(this.frequencyNavigation, ssidConfigOut.frequencyNavigation) &&
        Objects.equals(this.maxUserNumber, ssidConfigOut.maxUserNumber) &&
        Objects.equals(this.userSeparation, ssidConfigOut.userSeparation) &&
        Objects.equals(this.ssidAuth, ssidConfigOut.ssidAuth) &&
        Objects.equals(this.ssidPolicy, ssidConfigOut.ssidPolicy) &&
        Objects.equals(this.dot11r, ssidConfigOut.dot11r) &&
        Objects.equals(this.reassociateTimeout, ssidConfigOut.reassociateTimeout) &&
        Objects.equals(this.id, ssidConfigOut.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, tags, enable, connectionMode, vlans, hidedEnable, relativeRadios, frequencyNavigation, maxUserNumber, userSeparation, ssidAuth, ssidPolicy, dot11r, reassociateTimeout, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SsidConfigOut {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    connectionMode: ").append(toIndentedString(connectionMode)).append("\n");
    sb.append("    vlans: ").append(toIndentedString(vlans)).append("\n");
    sb.append("    hidedEnable: ").append(toIndentedString(hidedEnable)).append("\n");
    sb.append("    relativeRadios: ").append(toIndentedString(relativeRadios)).append("\n");
    sb.append("    frequencyNavigation: ").append(toIndentedString(frequencyNavigation)).append("\n");
    sb.append("    maxUserNumber: ").append(toIndentedString(maxUserNumber)).append("\n");
    sb.append("    userSeparation: ").append(toIndentedString(userSeparation)).append("\n");
    sb.append("    ssidAuth: ").append(toIndentedString(ssidAuth)).append("\n");
    sb.append("    ssidPolicy: ").append(toIndentedString(ssidPolicy)).append("\n");
    sb.append("    dot11r: ").append(toIndentedString(dot11r)).append("\n");
    sb.append("    reassociateTimeout: ").append(toIndentedString(reassociateTimeout)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

