/*
 * 堆叠管理
 * 堆叠管理第三方接口。 场景：创建堆叠操作的第三方接口。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 堆叠成员出参信息。
 */
@ApiModel(description = "堆叠成员出参信息。")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:19:11.966+08:00")
public class StackMemberOutput {
  @SerializedName("errcode")
  private String errcode = null;

  @SerializedName("errmsg")
  private String errmsg = null;

  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("esn")
  private String esn = null;

  @SerializedName("stackMemberId")
  private String stackMemberId = null;

  @SerializedName("slotId")
  private Integer slotId = null;

  @SerializedName("priority")
  private Integer priority = null;

  public StackMemberOutput errcode(String errcode) {
    this.errcode = errcode;
    return this;
  }

   /**
   * 错误码。
   * return errcode
  **/
  @ApiModelProperty(value = "错误码。")
  public String getErrcode() {
    return errcode;
  }

   /**
   * 错误码。
   * Param errcode
  **/
  public void setErrcode(String errcode) {
    this.errcode = errcode;
  }

  public StackMemberOutput errmsg(String errmsg) {
    this.errmsg = errmsg;
    return this;
  }

   /**
   * 错误信息。
   * return errmsg
  **/
  @ApiModelProperty(value = "错误信息。")
  public String getErrmsg() {
    return errmsg;
  }

   /**
   * 错误信息。
   * Param errmsg
  **/
  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }

  public StackMemberOutput deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * 设备ID，UUID格式。
   * return deviceId
  **/
  @ApiModelProperty(value = "设备ID，UUID格式。")
  public String getDeviceId() {
    return deviceId;
  }

   /**
   * 设备ID，UUID格式。
   * Param deviceId
  **/
  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public StackMemberOutput esn(String esn) {
    this.esn = esn;
    return this;
  }

   /**
   * 设备ESN。
   * return esn
  **/
  @ApiModelProperty(value = "设备ESN。")
  public String getEsn() {
    return esn;
  }

   /**
   * 设备ESN。
   * Param esn
  **/
  public void setEsn(String esn) {
    this.esn = esn;
  }

  public StackMemberOutput stackMemberId(String stackMemberId) {
    this.stackMemberId = stackMemberId;
    return this;
  }

   /**
   * 堆叠成员ID，UUID格式。
   * return stackMemberId
  **/
  @ApiModelProperty(value = "堆叠成员ID，UUID格式。")
  public String getStackMemberId() {
    return stackMemberId;
  }

   /**
   * 堆叠成员ID，UUID格式。
   * Param stackMemberId
  **/
  public void setStackMemberId(String stackMemberId) {
    this.stackMemberId = stackMemberId;
  }

  public StackMemberOutput slotId(Integer slotId) {
    this.slotId = slotId;
    return this;
  }

   /**
   * 设备堆叠编号。
   * return slotId
  **/
  @ApiModelProperty(value = "设备堆叠编号。")
  public Integer getSlotId() {
    return slotId;
  }

   /**
   * 设备堆叠编号。
   * Param slotId
  **/
  public void setSlotId(Integer slotId) {
    this.slotId = slotId;
  }

  public StackMemberOutput priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * 设备堆叠优先级。
   * return priority
  **/
  @ApiModelProperty(value = "设备堆叠优先级。")
  public Integer getPriority() {
    return priority;
  }

   /**
   * 设备堆叠优先级。
   * Param priority
  **/
  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StackMemberOutput stackMemberOutput = (StackMemberOutput) o;
    return Objects.equals(this.errcode, stackMemberOutput.errcode) &&
        Objects.equals(this.errmsg, stackMemberOutput.errmsg) &&
        Objects.equals(this.deviceId, stackMemberOutput.deviceId) &&
        Objects.equals(this.esn, stackMemberOutput.esn) &&
        Objects.equals(this.stackMemberId, stackMemberOutput.stackMemberId) &&
        Objects.equals(this.slotId, stackMemberOutput.slotId) &&
        Objects.equals(this.priority, stackMemberOutput.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errcode, errmsg, deviceId, esn, stackMemberId, slotId, priority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StackMemberOutput {\n");
    
    sb.append("    errcode: ").append(toIndentedString(errcode)).append("\n");
    sb.append("    errmsg: ").append(toIndentedString(errmsg)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    esn: ").append(toIndentedString(esn)).append("\n");
    sb.append("    stackMemberId: ").append(toIndentedString(stackMemberId)).append("\n");
    sb.append("    slotId: ").append(toIndentedString(slotId)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

