/*
 * 设备升级
 * · 查询设备文件 · 创建站点升级 · 查询站点升级 · 查询设备升级 · 取消设备升级 · 删除站点升级 · 重新升级设备 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * UpgradeDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:28.844+08:00")
public class UpgradeDetail {
  @SerializedName("deviceId")
  private UUID deviceId = null;

  @SerializedName("deviceName")
  private String deviceName = null;

  @SerializedName("esn")
  private String esn = null;

  @SerializedName("deviceStatus")
  private Integer deviceStatus = null;

  @SerializedName("deviceModel")
  private String deviceModel = null;

  @SerializedName("deviceType")
  private String deviceType = null;

  @SerializedName("siteName")
  private String siteName = null;

  @SerializedName("pkgVer")
  private String pkgVer = null;

  @SerializedName("pkgPercent")
  private Integer pkgPercent = null;

  @SerializedName("pkgUpStatus")
  private Integer pkgUpStatus = null;

  @SerializedName("patVer")
  private String patVer = null;

  @SerializedName("patPercent")
  private Integer patPercent = null;

  @SerializedName("patUpStatus")
  private Integer patUpStatus = null;

  @SerializedName("failureCause")
  private String failureCause = null;

  @SerializedName("rebootTime")
  private Long rebootTime = null;

  @SerializedName("downloadTime")
  private Long downloadTime = null;

  public UpgradeDetail deviceId(UUID deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * 设备ID。
   * return deviceId
  **/
  @ApiModelProperty(value = "设备ID。")
  public UUID getDeviceId() {
    return deviceId;
  }

   /**
   * 设备ID。
   * Param deviceId
  **/
  public void setDeviceId(UUID deviceId) {
    this.deviceId = deviceId;
  }

  public UpgradeDetail deviceName(String deviceName) {
    this.deviceName = deviceName;
    return this;
  }

   /**
   * 设备名称。
   * return deviceName
  **/
  @ApiModelProperty(value = "设备名称。")
  public String getDeviceName() {
    return deviceName;
  }

   /**
   * 设备名称。
   * Param deviceName
  **/
  public void setDeviceName(String deviceName) {
    this.deviceName = deviceName;
  }

  public UpgradeDetail esn(String esn) {
    this.esn = esn;
    return this;
  }

   /**
   * 设备ESN。
   * return esn
  **/
  @ApiModelProperty(value = "设备ESN。")
  public String getEsn() {
    return esn;
  }

   /**
   * 设备ESN。
   * Param esn
  **/
  public void setEsn(String esn) {
    this.esn = esn;
  }

  public UpgradeDetail deviceStatus(Integer deviceStatus) {
    this.deviceStatus = deviceStatus;
    return this;
  }

   /**
   * 设备状态。 0：正常 1：告警 3：离线 4：未注册 
   * minimum: 0
   * maximum: 10
   * return deviceStatus
  **/
  @ApiModelProperty(value = "设备状态。 0：正常 1：告警 3：离线 4：未注册 ")
  public Integer getDeviceStatus() {
    return deviceStatus;
  }

   /**
   * 设备状态。 0：正常 1：告警 3：离线 4：未注册 
   * minimum: 0
   * maximum: 10
   * Param deviceStatus
  **/
  public void setDeviceStatus(Integer deviceStatus) {
    this.deviceStatus = deviceStatus;
  }

  public UpgradeDetail deviceModel(String deviceModel) {
    this.deviceModel = deviceModel;
    return this;
  }

   /**
   * 设备款型。
   * return deviceModel
  **/
  @ApiModelProperty(value = "设备款型。")
  public String getDeviceModel() {
    return deviceModel;
  }

   /**
   * 设备款型。
   * Param deviceModel
  **/
  public void setDeviceModel(String deviceModel) {
    this.deviceModel = deviceModel;
  }

  public UpgradeDetail deviceType(String deviceType) {
    this.deviceType = deviceType;
    return this;
  }

   /**
   * 设备类型，取值为AP，AR，LSW，FW其中之一。
   * return deviceType
  **/
  @ApiModelProperty(value = "设备类型，取值为AP，AR，LSW，FW其中之一。")
  public String getDeviceType() {
    return deviceType;
  }

   /**
   * 设备类型，取值为AP，AR，LSW，FW其中之一。
   * Param deviceType
  **/
  public void setDeviceType(String deviceType) {
    this.deviceType = deviceType;
  }

  public UpgradeDetail siteName(String siteName) {
    this.siteName = siteName;
    return this;
  }

   /**
   * 站点名称。
   * return siteName
  **/
  @ApiModelProperty(value = "站点名称。")
  public String getSiteName() {
    return siteName;
  }

   /**
   * 站点名称。
   * Param siteName
  **/
  public void setSiteName(String siteName) {
    this.siteName = siteName;
  }

  public UpgradeDetail pkgVer(String pkgVer) {
    this.pkgVer = pkgVer;
    return this;
  }

   /**
   * 软件包版本。
   * return pkgVer
  **/
  @ApiModelProperty(value = "软件包版本。")
  public String getPkgVer() {
    return pkgVer;
  }

   /**
   * 软件包版本。
   * Param pkgVer
  **/
  public void setPkgVer(String pkgVer) {
    this.pkgVer = pkgVer;
  }

  public UpgradeDetail pkgPercent(Integer pkgPercent) {
    this.pkgPercent = pkgPercent;
    return this;
  }

   /**
   * 软件包下载进度。
   * minimum: 0
   * maximum: 100
   * return pkgPercent
  **/
  @ApiModelProperty(value = "软件包下载进度。")
  public Integer getPkgPercent() {
    return pkgPercent;
  }

   /**
   * 软件包下载进度。
   * minimum: 0
   * maximum: 100
   * Param pkgPercent
  **/
  public void setPkgPercent(Integer pkgPercent) {
    this.pkgPercent = pkgPercent;
  }

  public UpgradeDetail pkgUpStatus(Integer pkgUpStatus) {
    this.pkgUpStatus = pkgUpStatus;
    return this;
  }

   /**
   * 大包升级状态。 0：已创建升级任务，未升级 1：正在下载 2：已下载 5：升级完成 6：无需升级 8：升级失败 9：等待重启上线 10：正在激活大包 11：激活完成 16：取消升级成功 17：取消升级失败 18：下载停止 
   * minimum: 0
   * maximum: 20
   * return pkgUpStatus
  **/
  @ApiModelProperty(value = "大包升级状态。 0：已创建升级任务，未升级 1：正在下载 2：已下载 5：升级完成 6：无需升级 8：升级失败 9：等待重启上线 10：正在激活大包 11：激活完成 16：取消升级成功 17：取消升级失败 18：下载停止 ")
  public Integer getPkgUpStatus() {
    return pkgUpStatus;
  }

   /**
   * 大包升级状态。 0：已创建升级任务，未升级 1：正在下载 2：已下载 5：升级完成 6：无需升级 8：升级失败 9：等待重启上线 10：正在激活大包 11：激活完成 16：取消升级成功 17：取消升级失败 18：下载停止 
   * minimum: 0
   * maximum: 20
   * Param pkgUpStatus
  **/
  public void setPkgUpStatus(Integer pkgUpStatus) {
    this.pkgUpStatus = pkgUpStatus;
  }

  public UpgradeDetail patVer(String patVer) {
    this.patVer = patVer;
    return this;
  }

   /**
   * 补丁版本。
   * return patVer
  **/
  @ApiModelProperty(value = "补丁版本。")
  public String getPatVer() {
    return patVer;
  }

   /**
   * 补丁版本。
   * Param patVer
  **/
  public void setPatVer(String patVer) {
    this.patVer = patVer;
  }

  public UpgradeDetail patPercent(Integer patPercent) {
    this.patPercent = patPercent;
    return this;
  }

   /**
   * 补丁下载进度。
   * minimum: 0
   * maximum: 100
   * return patPercent
  **/
  @ApiModelProperty(value = "补丁下载进度。")
  public Integer getPatPercent() {
    return patPercent;
  }

   /**
   * 补丁下载进度。
   * minimum: 0
   * maximum: 100
   * Param patPercent
  **/
  public void setPatPercent(Integer patPercent) {
    this.patPercent = patPercent;
  }

  public UpgradeDetail patUpStatus(Integer patUpStatus) {
    this.patUpStatus = patUpStatus;
    return this;
  }

   /**
   * 补丁升级状态。 0：已创建升级任务，未升级 1：正在下载 2：已下载 5：升级完成 6：无需升级 8：升级失败 9：等待重启上线 12：正在补丁操作 13：补丁操作完成 16：取消升级成功 17：取消升级失败 18：下载停止 
   * minimum: 0
   * maximum: 20
   * return patUpStatus
  **/
  @ApiModelProperty(value = "补丁升级状态。 0：已创建升级任务，未升级 1：正在下载 2：已下载 5：升级完成 6：无需升级 8：升级失败 9：等待重启上线 12：正在补丁操作 13：补丁操作完成 16：取消升级成功 17：取消升级失败 18：下载停止 ")
  public Integer getPatUpStatus() {
    return patUpStatus;
  }

   /**
   * 补丁升级状态。 0：已创建升级任务，未升级 1：正在下载 2：已下载 5：升级完成 6：无需升级 8：升级失败 9：等待重启上线 12：正在补丁操作 13：补丁操作完成 16：取消升级成功 17：取消升级失败 18：下载停止 
   * minimum: 0
   * maximum: 20
   * Param patUpStatus
  **/
  public void setPatUpStatus(Integer patUpStatus) {
    this.patUpStatus = patUpStatus;
  }

  public UpgradeDetail failureCause(String failureCause) {
    this.failureCause = failureCause;
    return this;
  }

   /**
   * 失败原因。
   * return failureCause
  **/
  @ApiModelProperty(value = "失败原因。")
  public String getFailureCause() {
    return failureCause;
  }

   /**
   * 失败原因。
   * Param failureCause
  **/
  public void setFailureCause(String failureCause) {
    this.failureCause = failureCause;
  }

  public UpgradeDetail rebootTime(Long rebootTime) {
    this.rebootTime = rebootTime;
    return this;
  }

   /**
   * 重启时间。UTC时间。
   * minimum: 0
   * maximum: 4102416000
   * return rebootTime
  **/
  @ApiModelProperty(value = "重启时间。UTC时间。")
  public Long getRebootTime() {
    return rebootTime;
  }

   /**
   * 重启时间。UTC时间。
   * minimum: 0
   * maximum: 4102416000
   * Param rebootTime
  **/
  public void setRebootTime(Long rebootTime) {
    this.rebootTime = rebootTime;
  }

  public UpgradeDetail downloadTime(Long downloadTime) {
    this.downloadTime = downloadTime;
    return this;
  }

   /**
   * 下载时间。UTC时间。
   * minimum: 0
   * maximum: 4102416000
   * return downloadTime
  **/
  @ApiModelProperty(value = "下载时间。UTC时间。")
  public Long getDownloadTime() {
    return downloadTime;
  }

   /**
   * 下载时间。UTC时间。
   * minimum: 0
   * maximum: 4102416000
   * Param downloadTime
  **/
  public void setDownloadTime(Long downloadTime) {
    this.downloadTime = downloadTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpgradeDetail upgradeDetail = (UpgradeDetail) o;
    return Objects.equals(this.deviceId, upgradeDetail.deviceId) &&
        Objects.equals(this.deviceName, upgradeDetail.deviceName) &&
        Objects.equals(this.esn, upgradeDetail.esn) &&
        Objects.equals(this.deviceStatus, upgradeDetail.deviceStatus) &&
        Objects.equals(this.deviceModel, upgradeDetail.deviceModel) &&
        Objects.equals(this.deviceType, upgradeDetail.deviceType) &&
        Objects.equals(this.siteName, upgradeDetail.siteName) &&
        Objects.equals(this.pkgVer, upgradeDetail.pkgVer) &&
        Objects.equals(this.pkgPercent, upgradeDetail.pkgPercent) &&
        Objects.equals(this.pkgUpStatus, upgradeDetail.pkgUpStatus) &&
        Objects.equals(this.patVer, upgradeDetail.patVer) &&
        Objects.equals(this.patPercent, upgradeDetail.patPercent) &&
        Objects.equals(this.patUpStatus, upgradeDetail.patUpStatus) &&
        Objects.equals(this.failureCause, upgradeDetail.failureCause) &&
        Objects.equals(this.rebootTime, upgradeDetail.rebootTime) &&
        Objects.equals(this.downloadTime, upgradeDetail.downloadTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, deviceName, esn, deviceStatus, deviceModel, deviceType, siteName, pkgVer, pkgPercent, pkgUpStatus, patVer, patPercent, patUpStatus, failureCause, rebootTime, downloadTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpgradeDetail {\n");
    
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    esn: ").append(toIndentedString(esn)).append("\n");
    sb.append("    deviceStatus: ").append(toIndentedString(deviceStatus)).append("\n");
    sb.append("    deviceModel: ").append(toIndentedString(deviceModel)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    siteName: ").append(toIndentedString(siteName)).append("\n");
    sb.append("    pkgVer: ").append(toIndentedString(pkgVer)).append("\n");
    sb.append("    pkgPercent: ").append(toIndentedString(pkgPercent)).append("\n");
    sb.append("    pkgUpStatus: ").append(toIndentedString(pkgUpStatus)).append("\n");
    sb.append("    patVer: ").append(toIndentedString(patVer)).append("\n");
    sb.append("    patPercent: ").append(toIndentedString(patPercent)).append("\n");
    sb.append("    patUpStatus: ").append(toIndentedString(patUpStatus)).append("\n");
    sb.append("    failureCause: ").append(toIndentedString(failureCause)).append("\n");
    sb.append("    rebootTime: ").append(toIndentedString(rebootTime)).append("\n");
    sb.append("    downloadTime: ").append(toIndentedString(downloadTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

