/*
 * 终端用户认证授权
 * 终端用户认证开放API 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserAuthInputDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaSdnClientCodegen", date = "2019-12-17T15:18:51.931+08:00")
public class UserAuthInputDto {
  @SerializedName("authType")
  private Integer authType = null;

  @SerializedName("deviceMac")
  private String deviceMac = null;

  @SerializedName("ssid")
  private String ssid = null;

  @SerializedName("terminalIp")
  private String terminalIp = null;

  @SerializedName("terminalMac")
  private String terminalMac = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("password")
  private String password = null;

  public UserAuthInputDto authType(Integer authType) {
    this.authType = authType;
    return this;
  }

   /**
   * 认证类型。用户名密码：1；匿名认证：2；短信认证：3；passcode认证：6。默认为用户名密码认证(1)。
   * minimum: 1
   * maximum: 6
   * return authType
  **/
  @ApiModelProperty(value = "认证类型。用户名密码：1；匿名认证：2；短信认证：3；passcode认证：6。默认为用户名密码认证(1)。")
  public Integer getAuthType() {
    return authType;
  }

   /**
   * 认证类型。用户名密码：1；匿名认证：2；短信认证：3；passcode认证：6。默认为用户名密码认证(1)。
   * minimum: 1
   * maximum: 6
   * Param authType
  **/
  public void setAuthType(Integer authType) {
    this.authType = authType;
  }

  public UserAuthInputDto deviceMac(String deviceMac) {
    this.deviceMac = deviceMac;
    return this;
  }

   /**
   * 设备MAC地址。支持的格式：xx-xx-xx-xx-xx-xx/xx:xx:xx:xx:xx:xx/xxxxxxxxxxxx。
   * return deviceMac
  **/
  @ApiModelProperty(required = true, value = "设备MAC地址。支持的格式：xx-xx-xx-xx-xx-xx/xx:xx:xx:xx:xx:xx/xxxxxxxxxxxx。")
  public String getDeviceMac() {
    return deviceMac;
  }

   /**
   * 设备MAC地址。支持的格式：xx-xx-xx-xx-xx-xx/xx:xx:xx:xx:xx:xx/xxxxxxxxxxxx。
   * Param deviceMac
  **/
  public void setDeviceMac(String deviceMac) {
    this.deviceMac = deviceMac;
  }

  public UserAuthInputDto ssid(String ssid) {
    this.ssid = ssid;
    return this;
  }

   /**
   * AP SSID名称。
   * return ssid
  **/
  @ApiModelProperty(required = true, value = "AP SSID名称。")
  public String getSsid() {
    return ssid;
  }

   /**
   * AP SSID名称。
   * Param ssid
  **/
  public void setSsid(String ssid) {
    this.ssid = ssid;
  }

  public UserAuthInputDto terminalIp(String terminalIp) {
    this.terminalIp = terminalIp;
    return this;
  }

   /**
   * 终端IP地址，支持Ipv4和Ipv6地址，Ipv6地址例如：2000:0000:0000:0000:0000:0001。
   * return terminalIp
  **/
  @ApiModelProperty(required = true, value = "终端IP地址，支持Ipv4和Ipv6地址，Ipv6地址例如：2000:0000:0000:0000:0000:0001。")
  public String getTerminalIp() {
    return terminalIp;
  }

   /**
   * 终端IP地址，支持Ipv4和Ipv6地址，Ipv6地址例如：2000:0000:0000:0000:0000:0001。
   * Param terminalIp
  **/
  public void setTerminalIp(String terminalIp) {
    this.terminalIp = terminalIp;
  }

  public UserAuthInputDto terminalMac(String terminalMac) {
    this.terminalMac = terminalMac;
    return this;
  }

   /**
   * 终端MAC地址。支持的格式：xx-xx-xx-xx-xx-xx/xx:xx:xx:xx:xx:xx/xxxxxxxxxxxx。
   * return terminalMac
  **/
  @ApiModelProperty(required = true, value = "终端MAC地址。支持的格式：xx-xx-xx-xx-xx-xx/xx:xx:xx:xx:xx:xx/xxxxxxxxxxxx。")
  public String getTerminalMac() {
    return terminalMac;
  }

   /**
   * 终端MAC地址。支持的格式：xx-xx-xx-xx-xx-xx/xx:xx:xx:xx:xx:xx/xxxxxxxxxxxx。
   * Param terminalMac
  **/
  public void setTerminalMac(String terminalMac) {
    this.terminalMac = terminalMac;
  }

  public UserAuthInputDto userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * 用户名。
   * return userName
  **/
  @ApiModelProperty(required = true, value = "用户名。")
  public String getUserName() {
    return userName;
  }

   /**
   * 用户名。
   * Param userName
  **/
  public void setUserName(String userName) {
    this.userName = userName;
  }

  public UserAuthInputDto password(String password) {
    this.password = password;
    return this;
  }

   /**
   * 用户密码。
   * return password
  **/
  @ApiModelProperty(required = true, value = "用户密码。")
  public String getPassword() {
    return password;
  }

   /**
   * 用户密码。
   * Param password
  **/
  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAuthInputDto userAuthInputDto = (UserAuthInputDto) o;
    return Objects.equals(this.authType, userAuthInputDto.authType) &&
        Objects.equals(this.deviceMac, userAuthInputDto.deviceMac) &&
        Objects.equals(this.ssid, userAuthInputDto.ssid) &&
        Objects.equals(this.terminalIp, userAuthInputDto.terminalIp) &&
        Objects.equals(this.terminalMac, userAuthInputDto.terminalMac) &&
        Objects.equals(this.userName, userAuthInputDto.userName) &&
        Objects.equals(this.password, userAuthInputDto.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authType, deviceMac, ssid, terminalIp, terminalMac, userName, password);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAuthInputDto {\n");
    
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    deviceMac: ").append(toIndentedString(deviceMac)).append("\n");
    sb.append("    ssid: ").append(toIndentedString(ssid)).append("\n");
    sb.append("    terminalIp: ").append(toIndentedString(terminalIp)).append("\n");
    sb.append("    terminalMac: ").append(toIndentedString(terminalMac)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

