/*
 * 交换机STP保护配置
 * 主要特性： · 创建交换机STP保护配置 · 修改交换机STP保护配置 · 查询交换机STP保护配置 · 删除交换机STP保护配置 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiCallback;
import com.huawei.cloudcampus.api.ApiClient;
import com.huawei.cloudcampus.api.ApiException;
import com.huawei.cloudcampus.api.ApiResponse;
import com.huawei.cloudcampus.api.Configuration;
import com.huawei.cloudcampus.api.Pair;
import com.huawei.cloudcampus.api.ProgressRequestBody;
import com.huawei.cloudcampus.api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.huawei.cloudcampus.api.model.DeleteStpProtectionRequestDto;
import com.huawei.cloudcampus.api.model.DeleteStpProtectionResponseDto;
import com.huawei.cloudcampus.api.model.GetStpProtectionResponseDto;
import com.huawei.cloudcampus.api.model.StpProtectionRequestDto;
import com.huawei.cloudcampus.api.model.StpProtectionResponseDto;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LSWStpProtectionNorthboundApi {
    private ApiClient apiClient;

    public LSWStpProtectionNorthboundApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LSWStpProtectionNorthboundApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for createStpProtection
     * @param siteId 站点ID。 (required)
     * @param body 创建交换机STP保护配置信息。 (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createStpProtectionCall(UUID siteId, StpProtectionRequestDto body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/controller/campus/v1/networkservice/networkconfig/net/lswstpprotection/sites/{siteId}/stpprotection"
            .replaceAll("\\{" + "siteId" + "\\}", apiClient.escapeString(siteId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createStpProtectionValidateBeforeCall(UUID siteId, StpProtectionRequestDto body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'siteId' is set
        if (siteId == null) {
            throw new ApiException("Missing the required parameter 'siteId' when calling createStpProtection(Async)");
        }
        
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling createStpProtection(Async)");
        }
        
        
        com.squareup.okhttp.Call call = createStpProtectionCall(siteId, body, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 创建交换机STP保护配置
     * ## 典型场景 ##    提供配置参数的接口，创建交换机STP保护配置。 ## 接口功能 ##    创建交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 创建交换机STP保护配置信息。 (required)
     * @return StpProtectionResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public StpProtectionResponseDto createStpProtection(UUID siteId, StpProtectionRequestDto body) throws ApiException {
        ApiResponse<StpProtectionResponseDto> resp = createStpProtectionWithHttpInfo(siteId, body);
        return resp.getData();
    }

    /**
     * 创建交换机STP保护配置
     * ## 典型场景 ##    提供配置参数的接口，创建交换机STP保护配置。 ## 接口功能 ##    创建交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 创建交换机STP保护配置信息。 (required)
     * @return ApiResponse&lt;StpProtectionResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<StpProtectionResponseDto> createStpProtectionWithHttpInfo(UUID siteId, StpProtectionRequestDto body) throws ApiException {
        com.squareup.okhttp.Call call = createStpProtectionValidateBeforeCall(siteId, body, null, null);
        Type localVarReturnType = new TypeToken<StpProtectionResponseDto>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 创建交换机STP保护配置 (asynchronously)
     * ## 典型场景 ##    提供配置参数的接口，创建交换机STP保护配置。 ## 接口功能 ##    创建交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 创建交换机STP保护配置信息。 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createStpProtectionAsync(UUID siteId, StpProtectionRequestDto body, final ApiCallback<StpProtectionResponseDto> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createStpProtectionValidateBeforeCall(siteId, body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<StpProtectionResponseDto>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for deleteStpProtection
     * @param siteId 站点ID。 (required)
     * @param body 删除交换机STP保护配置请求参数体。 (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteStpProtectionCall(UUID siteId, DeleteStpProtectionRequestDto body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/controller/campus/v1/networkservice/networkconfig/net/lswstpprotection/sites/{siteId}/stpprotection/batch-delete"
            .replaceAll("\\{" + "siteId" + "\\}", apiClient.escapeString(siteId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteStpProtectionValidateBeforeCall(UUID siteId, DeleteStpProtectionRequestDto body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'siteId' is set
        if (siteId == null) {
            throw new ApiException("Missing the required parameter 'siteId' when calling deleteStpProtection(Async)");
        }
        
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling deleteStpProtection(Async)");
        }
        
        
        com.squareup.okhttp.Call call = deleteStpProtectionCall(siteId, body, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 删除交换机STP保护配置
     * ## 典型场景 ##    提供删除配置参数的接口，删除交换机STP保护配置。 ## 接口功能 ##    删除交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 删除交换机STP保护配置请求参数体。 (required)
     * @return DeleteStpProtectionResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public DeleteStpProtectionResponseDto deleteStpProtection(UUID siteId, DeleteStpProtectionRequestDto body) throws ApiException {
        ApiResponse<DeleteStpProtectionResponseDto> resp = deleteStpProtectionWithHttpInfo(siteId, body);
        return resp.getData();
    }

    /**
     * 删除交换机STP保护配置
     * ## 典型场景 ##    提供删除配置参数的接口，删除交换机STP保护配置。 ## 接口功能 ##    删除交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 删除交换机STP保护配置请求参数体。 (required)
     * @return ApiResponse&lt;DeleteStpProtectionResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<DeleteStpProtectionResponseDto> deleteStpProtectionWithHttpInfo(UUID siteId, DeleteStpProtectionRequestDto body) throws ApiException {
        com.squareup.okhttp.Call call = deleteStpProtectionValidateBeforeCall(siteId, body, null, null);
        Type localVarReturnType = new TypeToken<DeleteStpProtectionResponseDto>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 删除交换机STP保护配置 (asynchronously)
     * ## 典型场景 ##    提供删除配置参数的接口，删除交换机STP保护配置。 ## 接口功能 ##    删除交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 删除交换机STP保护配置请求参数体。 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteStpProtectionAsync(UUID siteId, DeleteStpProtectionRequestDto body, final ApiCallback<DeleteStpProtectionResponseDto> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteStpProtectionValidateBeforeCall(siteId, body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<DeleteStpProtectionResponseDto>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getStpProtection
     * @param siteId 站点ID。 (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getStpProtectionCall(UUID siteId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/controller/campus/v1/networkservice/networkconfig/net/lswstpprotection/sites/{siteId}/stpprotection"
            .replaceAll("\\{" + "siteId" + "\\}", apiClient.escapeString(siteId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getStpProtectionValidateBeforeCall(UUID siteId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'siteId' is set
        if (siteId == null) {
            throw new ApiException("Missing the required parameter 'siteId' when calling getStpProtection(Async)");
        }
        
        
        com.squareup.okhttp.Call call = getStpProtectionCall(siteId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 查询交换机STP保护配置
     * ## 典型场景 ##    提供查询配置参数的接口，查询交换机STP保护配置信息。 ## 接口功能 ##    查询交换机STP保护配置信息。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @return GetStpProtectionResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public GetStpProtectionResponseDto getStpProtection(UUID siteId) throws ApiException {
        ApiResponse<GetStpProtectionResponseDto> resp = getStpProtectionWithHttpInfo(siteId);
        return resp.getData();
    }

    /**
     * 查询交换机STP保护配置
     * ## 典型场景 ##    提供查询配置参数的接口，查询交换机STP保护配置信息。 ## 接口功能 ##    查询交换机STP保护配置信息。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @return ApiResponse&lt;GetStpProtectionResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<GetStpProtectionResponseDto> getStpProtectionWithHttpInfo(UUID siteId) throws ApiException {
        com.squareup.okhttp.Call call = getStpProtectionValidateBeforeCall(siteId, null, null);
        Type localVarReturnType = new TypeToken<GetStpProtectionResponseDto>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 查询交换机STP保护配置 (asynchronously)
     * ## 典型场景 ##    提供查询配置参数的接口，查询交换机STP保护配置信息。 ## 接口功能 ##    查询交换机STP保护配置信息。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getStpProtectionAsync(UUID siteId, final ApiCallback<GetStpProtectionResponseDto> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getStpProtectionValidateBeforeCall(siteId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<GetStpProtectionResponseDto>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for updateStpProtection
     * @param siteId 站点ID。 (required)
     * @param body 修改交换机STP保护配置参数体。 (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call updateStpProtectionCall(UUID siteId, StpProtectionRequestDto body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/controller/campus/v1/networkservice/networkconfig/net/lswstpprotection/sites/{siteId}/stpprotection"
            .replaceAll("\\{" + "siteId" + "\\}", apiClient.escapeString(siteId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call updateStpProtectionValidateBeforeCall(UUID siteId, StpProtectionRequestDto body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'siteId' is set
        if (siteId == null) {
            throw new ApiException("Missing the required parameter 'siteId' when calling updateStpProtection(Async)");
        }
        
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling updateStpProtection(Async)");
        }
        
        
        com.squareup.okhttp.Call call = updateStpProtectionCall(siteId, body, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 修改交换机STP保护配置
     * ## 典型场景 ##    提供配置参数的接口，修改交换机STP保护配置。 ## 接口功能 ##    修改交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 修改交换机STP保护配置参数体。 (required)
     * @return StpProtectionResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public StpProtectionResponseDto updateStpProtection(UUID siteId, StpProtectionRequestDto body) throws ApiException {
        ApiResponse<StpProtectionResponseDto> resp = updateStpProtectionWithHttpInfo(siteId, body);
        return resp.getData();
    }

    /**
     * 修改交换机STP保护配置
     * ## 典型场景 ##    提供配置参数的接口，修改交换机STP保护配置。 ## 接口功能 ##    修改交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 修改交换机STP保护配置参数体。 (required)
     * @return ApiResponse&lt;StpProtectionResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<StpProtectionResponseDto> updateStpProtectionWithHttpInfo(UUID siteId, StpProtectionRequestDto body) throws ApiException {
        com.squareup.okhttp.Call call = updateStpProtectionValidateBeforeCall(siteId, body, null, null);
        Type localVarReturnType = new TypeToken<StpProtectionResponseDto>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 修改交换机STP保护配置 (asynchronously)
     * ## 典型场景 ##    提供配置参数的接口，修改交换机STP保护配置。 ## 接口功能 ##    修改交换机STP保护配置。 ## 接口约束 ##    该接口必须在租户内，存在交换机设备的站点内使用。 
     * @param siteId 站点ID。 (required)
     * @param body 修改交换机STP保护配置参数体。 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call updateStpProtectionAsync(UUID siteId, StpProtectionRequestDto body, final ApiCallback<StpProtectionResponseDto> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = updateStpProtectionValidateBeforeCall(siteId, body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<StpProtectionResponseDto>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
