/*
 * 设备定时重启
 * · 创建或修改定时重启、延时重启设备任务 · 查询重启设备任务的状态 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiCallback;
import com.huawei.cloudcampus.api.ApiClient;
import com.huawei.cloudcampus.api.ApiException;
import com.huawei.cloudcampus.api.ApiResponse;
import com.huawei.cloudcampus.api.Configuration;
import com.huawei.cloudcampus.api.Pair;
import com.huawei.cloudcampus.api.ProgressRequestBody;
import com.huawei.cloudcampus.api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.huawei.cloudcampus.api.model.GetRebootStatusResp;
import com.huawei.cloudcampus.api.model.PeriodRebootDeviceResp;
import com.huawei.cloudcampus.api.model.ReriodRebootDeviceParam;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PeriodRebootDeviceApi {
    private ApiClient apiClient;

    public PeriodRebootDeviceApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PeriodRebootDeviceApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getRebootTaskStatus
     * @param deviceId 设备ID，UUID格式。 (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getRebootTaskStatusCall(String deviceId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/controller/campus/v1/oamservice/device-reboot/{deviceId}"
            .replaceAll("\\{" + "deviceId" + "\\}", apiClient.escapeString(deviceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getRebootTaskStatusValidateBeforeCall(String deviceId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'deviceId' is set
        if (deviceId == null) {
            throw new ApiException("Missing the required parameter 'deviceId' when calling getRebootTaskStatus(Async)");
        }
        
        
        com.squareup.okhttp.Call call = getRebootTaskStatusCall(deviceId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 查询设备定时重启任务
     * ## 典型场景 ##    查询重启任务状态。 ## 接口功能 ##    基于设备维度查询重启任务状态。 ## 接口约束 ##    北向接口管理员可以访问。 
     * @param deviceId 设备ID，UUID格式。 (required)
     * @return GetRebootStatusResp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public GetRebootStatusResp getRebootTaskStatus(String deviceId) throws ApiException {
        ApiResponse<GetRebootStatusResp> resp = getRebootTaskStatusWithHttpInfo(deviceId);
        return resp.getData();
    }

    /**
     * 查询设备定时重启任务
     * ## 典型场景 ##    查询重启任务状态。 ## 接口功能 ##    基于设备维度查询重启任务状态。 ## 接口约束 ##    北向接口管理员可以访问。 
     * @param deviceId 设备ID，UUID格式。 (required)
     * @return ApiResponse&lt;GetRebootStatusResp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<GetRebootStatusResp> getRebootTaskStatusWithHttpInfo(String deviceId) throws ApiException {
        com.squareup.okhttp.Call call = getRebootTaskStatusValidateBeforeCall(deviceId, null, null);
        Type localVarReturnType = new TypeToken<GetRebootStatusResp>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 查询设备定时重启任务 (asynchronously)
     * ## 典型场景 ##    查询重启任务状态。 ## 接口功能 ##    基于设备维度查询重启任务状态。 ## 接口约束 ##    北向接口管理员可以访问。 
     * @param deviceId 设备ID，UUID格式。 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getRebootTaskStatusAsync(String deviceId, final ApiCallback<GetRebootStatusResp> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getRebootTaskStatusValidateBeforeCall(deviceId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<GetRebootStatusResp>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for periodRebootDevice
     * @param deviceId 设备ID，UUID格式。 (required)
     * @param taskParam 参数。 (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call periodRebootDeviceCall(String deviceId, ReriodRebootDeviceParam taskParam, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = taskParam;
        
        // create path and map variables
        String localVarPath = "/controller/campus/v1/oamservice/device-reboot/{deviceId}"
            .replaceAll("\\{" + "deviceId" + "\\}", apiClient.escapeString(deviceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call periodRebootDeviceValidateBeforeCall(String deviceId, ReriodRebootDeviceParam taskParam, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'deviceId' is set
        if (deviceId == null) {
            throw new ApiException("Missing the required parameter 'deviceId' when calling periodRebootDevice(Async)");
        }
        
        // verify the required parameter 'taskParam' is set
        if (taskParam == null) {
            throw new ApiException("Missing the required parameter 'taskParam' when calling periodRebootDevice(Async)");
        }
        
        
        com.squareup.okhttp.Call call = periodRebootDeviceCall(deviceId, taskParam, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 设置设备定时重启任务
     * ## 典型场景 ##    提供创建或更新定时重启设备任务接口。 ## 接口功能 ##    基于设备维度创建或更新定时重启设备任务。 ## 接口约束 ##    北向接口管理员可以访问。 
     * @param deviceId 设备ID，UUID格式。 (required)
     * @param taskParam 参数。 (required)
     * @return PeriodRebootDeviceResp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public PeriodRebootDeviceResp periodRebootDevice(String deviceId, ReriodRebootDeviceParam taskParam) throws ApiException {
        ApiResponse<PeriodRebootDeviceResp> resp = periodRebootDeviceWithHttpInfo(deviceId, taskParam);
        return resp.getData();
    }

    /**
     * 设置设备定时重启任务
     * ## 典型场景 ##    提供创建或更新定时重启设备任务接口。 ## 接口功能 ##    基于设备维度创建或更新定时重启设备任务。 ## 接口约束 ##    北向接口管理员可以访问。 
     * @param deviceId 设备ID，UUID格式。 (required)
     * @param taskParam 参数。 (required)
     * @return ApiResponse&lt;PeriodRebootDeviceResp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<PeriodRebootDeviceResp> periodRebootDeviceWithHttpInfo(String deviceId, ReriodRebootDeviceParam taskParam) throws ApiException {
        com.squareup.okhttp.Call call = periodRebootDeviceValidateBeforeCall(deviceId, taskParam, null, null);
        Type localVarReturnType = new TypeToken<PeriodRebootDeviceResp>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 设置设备定时重启任务 (asynchronously)
     * ## 典型场景 ##    提供创建或更新定时重启设备任务接口。 ## 接口功能 ##    基于设备维度创建或更新定时重启设备任务。 ## 接口约束 ##    北向接口管理员可以访问。 
     * @param deviceId 设备ID，UUID格式。 (required)
     * @param taskParam 参数。 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call periodRebootDeviceAsync(String deviceId, ReriodRebootDeviceParam taskParam, final ApiCallback<PeriodRebootDeviceResp> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = periodRebootDeviceValidateBeforeCall(deviceId, taskParam, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<PeriodRebootDeviceResp>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
