/*
 * 运维ping/trace探测
 * ping/trace探测第三方接口。 · 创建ping探测任务 · 查询ping探测结果 · 创建trace探测任务 · 查询trace探测结果 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiCallback;
import com.huawei.cloudcampus.api.ApiClient;
import com.huawei.cloudcampus.api.ApiException;
import com.huawei.cloudcampus.api.ApiResponse;
import com.huawei.cloudcampus.api.Configuration;
import com.huawei.cloudcampus.api.Pair;
import com.huawei.cloudcampus.api.ProgressRequestBody;
import com.huawei.cloudcampus.api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.huawei.cloudcampus.api.model.TraceDiagnoseDto;
import com.huawei.cloudcampus.api.model.TraceReplyResponse;
import com.huawei.cloudcampus.api.model.TraceTaskResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TraceDiagnoseServiceApi {
    private ApiClient apiClient;

    public TraceDiagnoseServiceApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TraceDiagnoseServiceApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for createTraceTask
     * @param request 请求参数。 (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createTraceTaskCall(TraceDiagnoseDto request, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = request;
        
        // create path and map variables
        String localVarPath = "/controller/campus/v1/oamservice/trace";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createTraceTaskValidateBeforeCall(TraceDiagnoseDto request, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'request' is set
        if (request == null) {
            throw new ApiException("Missing the required parameter 'request' when calling createTraceTask(Async)");
        }
        
        
        com.squareup.okhttp.Call call = createTraceTaskCall(request, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 创建Trace探测任务
     * ## 典型场景 ##  创建Trace探测任务。 ## 接口功能 ##  创建Trace探测任务。 ## 接口约束 ##  只有租户管理员获取token并建立会话后才能调用该接口。 
     * @param request 请求参数。 (required)
     * @return TraceTaskResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public TraceTaskResponse createTraceTask(TraceDiagnoseDto request) throws ApiException {
        ApiResponse<TraceTaskResponse> resp = createTraceTaskWithHttpInfo(request);
        return resp.getData();
    }

    /**
     * 创建Trace探测任务
     * ## 典型场景 ##  创建Trace探测任务。 ## 接口功能 ##  创建Trace探测任务。 ## 接口约束 ##  只有租户管理员获取token并建立会话后才能调用该接口。 
     * @param request 请求参数。 (required)
     * @return ApiResponse&lt;TraceTaskResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<TraceTaskResponse> createTraceTaskWithHttpInfo(TraceDiagnoseDto request) throws ApiException {
        com.squareup.okhttp.Call call = createTraceTaskValidateBeforeCall(request, null, null);
        Type localVarReturnType = new TypeToken<TraceTaskResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 创建Trace探测任务 (asynchronously)
     * ## 典型场景 ##  创建Trace探测任务。 ## 接口功能 ##  创建Trace探测任务。 ## 接口约束 ##  只有租户管理员获取token并建立会话后才能调用该接口。 
     * @param request 请求参数。 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createTraceTaskAsync(TraceDiagnoseDto request, final ApiCallback<TraceTaskResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createTraceTaskValidateBeforeCall(request, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<TraceTaskResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for queryTraceTaskByTaskId
     * @param taskId Trace探测任务ID，格式UUID。 (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call queryTraceTaskByTaskIdCall(String taskId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/controller/campus/v1/oamservice/trace/{taskId}"
            .replaceAll("\\{" + "taskId" + "\\}", apiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call queryTraceTaskByTaskIdValidateBeforeCall(String taskId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException("Missing the required parameter 'taskId' when calling queryTraceTaskByTaskId(Async)");
        }
        
        
        com.squareup.okhttp.Call call = queryTraceTaskByTaskIdCall(taskId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 查询Trace探测结果
     * ## 典型场景 ##  根据taskId查询trace任务。 ## 接口功能 ##  查询Trace探测任务。 ## 接口约束 ##  只有租户管理员获取token并建立会话后才能调用该接口。 
     * @param taskId Trace探测任务ID，格式UUID。 (required)
     * @return TraceReplyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public TraceReplyResponse queryTraceTaskByTaskId(String taskId) throws ApiException {
        ApiResponse<TraceReplyResponse> resp = queryTraceTaskByTaskIdWithHttpInfo(taskId);
        return resp.getData();
    }

    /**
     * 查询Trace探测结果
     * ## 典型场景 ##  根据taskId查询trace任务。 ## 接口功能 ##  查询Trace探测任务。 ## 接口约束 ##  只有租户管理员获取token并建立会话后才能调用该接口。 
     * @param taskId Trace探测任务ID，格式UUID。 (required)
     * @return ApiResponse&lt;TraceReplyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<TraceReplyResponse> queryTraceTaskByTaskIdWithHttpInfo(String taskId) throws ApiException {
        com.squareup.okhttp.Call call = queryTraceTaskByTaskIdValidateBeforeCall(taskId, null, null);
        Type localVarReturnType = new TypeToken<TraceReplyResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * 查询Trace探测结果 (asynchronously)
     * ## 典型场景 ##  根据taskId查询trace任务。 ## 接口功能 ##  查询Trace探测任务。 ## 接口约束 ##  只有租户管理员获取token并建立会话后才能调用该接口。 
     * @param taskId Trace探测任务ID，格式UUID。 (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call queryTraceTaskByTaskIdAsync(String taskId, final ApiCallback<TraceReplyResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = queryTraceTaskByTaskIdValidateBeforeCall(taskId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<TraceReplyResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
