/*
 * AP网口IOT插卡管理
 * AP网口IOT插卡查询及操作接口。 场景：对AP网口IOT插卡查询及操作的第三方接口。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiException;
import com.huawei.cloudcampus.api.model.CardOperationOutputDto;
import com.huawei.cloudcampus.api.model.EthernetCardOutputDto;
import com.huawei.cloudcampus.api.model.IotCardOperationDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApIotCardOpenapiApi
 */
@Ignore
public class ApIotCardOpenapiApiTest {

    private final ApIotCardOpenapiApi api = new ApIotCardOpenapiApi();

    
    /**
     * 配置AP网口IOT插卡
     *
     * ## 典型场景 ##   操作插卡。 ## 接口功能 ##   对插卡进行重启、重置网络配置等操作。 ## 接口约束 ##   该接口支持租户下北向接口管理访问，必须在用户会话建立后使用。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cardOperationTest() throws ApiException {
        IotCardOperationDto requestDto = null;
        CardOperationOutputDto response = api.cardOperation(requestDto);

        // TODO: test validations
    }
    
    /**
     * 查询AP网口IOT插卡
     *
     * ## 典型场景 ##   查询AP网口IOT插卡列表。 ## 接口功能 ##   查询AP网口IOT插卡列表。 ## 接口约束 ##   该接口支持租户下北向接口管理访问，必须在用户会话建立后使用。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryEthernetCardListTest() throws ApiException {
        String siteId = null;
        String keyword = null;
        Integer pageSize = null;
        Integer pageIndex = null;
        EthernetCardOutputDto response = api.queryEthernetCardList(siteId, keyword, pageSize, pageIndex);

        // TODO: test validations
    }
    
}
