/*
 * TACACS模板管理
 * TACACS模板配置北向接口，主要特性：  * 创建tacacs模板。 * 修改tacacs模板。 * 查询tacacs模板。 * 删除tacacs模板。 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiException;
import com.huawei.cloudcampus.api.model.CreateTacacsTmplInfoDto;
import com.huawei.cloudcampus.api.model.CreateTacacsTmplResponse;
import com.huawei.cloudcampus.api.model.DeleteTacacsTmplResponses;
import com.huawei.cloudcampus.api.model.DeleteTacacsTmplReuest;
import com.huawei.cloudcampus.api.model.EditTacacsTmplResponse;
import com.huawei.cloudcampus.api.model.GetTacacsTmplResponse;
import java.util.UUID;
import com.huawei.cloudcampus.api.model.UpdateTacacsTmplInfoDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NetWorkServiceTacacsTmplApi
 */
@Ignore
public class NetWorkServiceTacacsTmplApiTest {

    private final NetWorkServiceTacacsTmplApi api = new NetWorkServiceTacacsTmplApi();

    
    /**
     * 创建TACACS模板
     *
     * ## 典型场景 ##    创建Tacacs模板。 ## 接口功能 ##   Tacacs模板创建接口（包含Tacacs模板对应的名称、描述、认证服务器地址、端口等）。 ## 接口约束 ##    该接口基于租户下；优先配置主服务器地址/端口。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTacacsTmplTest() throws ApiException {
        CreateTacacsTmplInfoDto body = null;
        CreateTacacsTmplResponse response = api.createTacacsTmpl(body);

        // TODO: test validations
    }
    
    /**
     * 删除TACACS模板
     *
     * ## 典型场景 ##    删除配置模板列表信息。 ## 接口功能 ##   Tacacs模板删除接口（包含Tacacs模板对应的名称、描述、认证服务器地址、端口等）。 ## 接口约束 ##    该接口基于租户下；如果模板被引用不可删除。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTacacsTmplTest() throws ApiException {
        DeleteTacacsTmplReuest body = null;
        DeleteTacacsTmplResponses response = api.deleteTacacsTmpl(body);

        // TODO: test validations
    }
    
    /**
     * 修改TACACS模板
     *
     * ## 典型场景 ##    修改Tacacs模板。 ## 接口功能 ##   Tacacs模板修改接口（包含Tacacs模板对应的名称、描述、认证服务器地址、端口等）。 ## 接口约束 ##    该接口基于租户下；优先配置主服务器地址/端口。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editTacacsTmplTest() throws ApiException {
        UUID id = null;
        UpdateTacacsTmplInfoDto body = null;
        EditTacacsTmplResponse response = api.editTacacsTmpl(id, body);

        // TODO: test validations
    }
    
    /**
     * 查询TACACS模板
     *
     * ## 典型场景 ##    查询配置模板列表信息。 ## 接口功能 ##   Tacacs模板查询接口（包含Tacacs模板对应的名称、描述、认证服务器地址、端口等）。 ## 接口约束 ##    该接口基于租户下；优先配置主服务器地址/端口。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTacacsTmplTest() throws ApiException {
        GetTacacsTmplResponse response = api.getTacacsTmpl();

        // TODO: test validations
    }
    
}
