/*
 * 设备基础性能数据信息查询
 * · 查询设备网络速率历史数据 · 查询站点维度TopN设备或者全部设备的上行流量、下行流量 · 查询站点维度设备连接终端数历史数据 · 查询单设备连接终端数历史数据 · 查询租户维度下设备状态历史数据 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiException;
import com.huawei.cloudcampus.api.model.DeviceCountTrendResp;
import com.huawei.cloudcampus.api.model.DevicePerformanceResp;
import com.huawei.cloudcampus.api.model.DeviceStationStatisticResp;
import com.huawei.cloudcampus.api.model.DeviceTrafficStatisticResp;
import com.huawei.cloudcampus.api.model.NetworkTrafficResp;
import com.huawei.cloudcampus.api.model.SiteStationStatisticResp;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PerformanceOpenApiApi
 */
@Ignore
public class PerformanceOpenApiApiTest {

    private final PerformanceOpenApiApi api = new PerformanceOpenApiApi();

    
    /**
     * 查询租户维度下设备状态历史数据列表
     *
     * ## 典型场景 ##    提供查询租户维度下设备状态历史数据             ## 接口功能 ##    查询租户维度下设备状态历史数据 ## 接口约束 ##    无。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryDeviceCountTrendTest() throws ApiException {
        String mode = null;
        String timeDimension = null;
        Long beginTime = null;
        Long endTime = null;
        DeviceCountTrendResp response = api.queryDeviceCountTrend(mode, timeDimension, beginTime, endTime);

        // TODO: test validations
    }
    
    /**
     * 查询设备连接终端数历史数据
     *
     * ## 典型场景 ##    提供查询设备连接终端数历史数据的接口。 ## 接口功能 ##    支持查询设备连接终端数历史数据。 ## 接口约束 ##    无。   
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryDeviceStationStatisticTest() throws ApiException {
        UUID deviceId = null;
        String timeDimension = null;
        Long beginTime = null;
        Long endTime = null;
        DeviceStationStatisticResp response = api.queryDeviceStationStatistic(deviceId, timeDimension, beginTime, endTime);

        // TODO: test validations
    }
    
    /**
     * 查询站点维度TopN设备或者全部设备的上行流量、下行流量
     *
     * ## 典型场景 ##    提供查询站点维度TopN设备或者全部设备的上行流量、下行流量的接口。           ## 接口功能 ##    支持查询站点维度TopN设备或者全部设备的上行流量、下行流量。 ## 接口约束 ##    无。   
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryDeviceTrafficTest() throws ApiException {
        UUID siteId = null;
        String timeDimension = null;
        Integer top = null;
        Long beginTime = null;
        Long endTime = null;
        DeviceTrafficStatisticResp response = api.queryDeviceTraffic(siteId, timeDimension, top, beginTime, endTime);

        // TODO: test validations
    }
    
    /**
     * 查询设备网络速率历史数据
     *
     * ## 典型场景 ##    提供查询设备网络速率历史数据的接口。           ## 接口功能 ##    查询设备网络速率历史数据。 ## 接口约束 ##    无。   
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryNetworkTrafficTest() throws ApiException {
        String mode = null;
        UUID id = null;
        String timeDimension = null;
        Long beginTime = null;
        Long endTime = null;
        NetworkTrafficResp response = api.queryNetworkTraffic(mode, id, timeDimension, beginTime, endTime);

        // TODO: test validations
    }
    
    /**
     * 查询站点维度设备连接终端数历史数据
     *
     * ## 典型场景 ##    提供查询站点维度设备连接终端数历史数据的接口。           ## 接口功能 ##    支持查询站点维度设备连接终端数历史数据。 ## 接口约束 ##    无。   
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void querySiteStationStatisticTest() throws ApiException {
        UUID siteId = null;
        String timeDimension = null;
        Long beginTime = null;
        Long endTime = null;
        String deviceType = null;
        SiteStationStatisticResp response = api.querySiteStationStatistic(siteId, timeDimension, beginTime, endTime, deviceType);

        // TODO: test validations
    }
    
    /**
     * 查询单设备的性能数据
     *
     * ## 典型场景 ##  查询单个设备基本信息、总流量以及最近一次设备上报的终端连接数、CPU利用率、上行速率、下行速率。           ## 接口功能 ##  单个设备基本信息、总流量以及最近一次设备上报的终端连接数、CPU利用率、上行速率、下行速率。 ## 接口约束 ##  无。   
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void singleDevicePerformanceDetailTest() throws ApiException {
        UUID deviceId = null;
        DevicePerformanceResp response = api.singleDevicePerformanceDetail(deviceId);

        // TODO: test validations
    }
    
}
