/*
 * 拓扑管理
 * 拓扑管理第三方北向接口。 1、查询LACP LAG信息 2、查询LLDP信息 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiException;
import com.huawei.cloudcampus.api.model.LacpLagInfoResultDto;
import com.huawei.cloudcampus.api.model.NeighborsInfoResultDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TopoMgrServiceApi
 */
@Ignore
public class TopoMgrServiceApiTest {

    private final TopoMgrServiceApi api = new TopoMgrServiceApi();

    
    /**
     * 查询LACP LAG信息
     *
     * ## 典型场景 ##  根据设备ID查询LACP LAG信息。 ## 接口功能 ##  查询LACP LAG信息。 ## 接口约束 ##  1、当前仅LSW支持该接口。  2、该接口必须在用户会话建立后使用。  3、该接口需从设备查询信息，数据量大时会导致查询响应慢。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLacpLagInfoTest() throws ApiException {
        String deviceId = null;
        LacpLagInfoResultDto response = api.getLacpLagInfo(deviceId);

        // TODO: test validations
    }
    
    /**
     * 查询LLDP信息
     *
     * ## 典型场景 ##  根据设备ID查询LLDP信息。 ## 接口功能 ##  查询LLDP信息。 ## 接口约束 ##  1、当前仅LSW和云AP支持该接口。  2、该接口必须在用户会话建立后使用。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNeighborsInfoTest() throws ApiException {
        String deviceId = null;
        String localIfName = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        NeighborsInfoResultDto response = api.getNeighborsInfo(deviceId, localIfName, pageIndex, pageSize);

        // TODO: test validations
    }
    
}
