/*
 * 运维ping/trace探测
 * ping/trace探测第三方接口。 · 创建ping探测任务 · 查询ping探测结果 · 创建trace探测任务 · 查询trace探测结果 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiException;
import com.huawei.cloudcampus.api.model.TraceDiagnoseDto;
import com.huawei.cloudcampus.api.model.TraceReplyResponse;
import com.huawei.cloudcampus.api.model.TraceTaskResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TraceDiagnoseServiceApi
 */
@Ignore
public class TraceDiagnoseServiceApiTest {

    private final TraceDiagnoseServiceApi api = new TraceDiagnoseServiceApi();

    
    /**
     * 创建Trace探测任务
     *
     * ## 典型场景 ##  创建Trace探测任务。 ## 接口功能 ##  创建Trace探测任务。 ## 接口约束 ##  只有租户管理员获取token并建立会话后才能调用该接口。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTraceTaskTest() throws ApiException {
        TraceDiagnoseDto request = null;
        TraceTaskResponse response = api.createTraceTask(request);

        // TODO: test validations
    }
    
    /**
     * 查询Trace探测结果
     *
     * ## 典型场景 ##  根据taskId查询trace任务。 ## 接口功能 ##  查询Trace探测任务。 ## 接口约束 ##  只有租户管理员获取token并建立会话后才能调用该接口。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryTraceTaskByTaskIdTest() throws ApiException {
        String taskId = null;
        TraceReplyResponse response = api.queryTraceTaskByTaskId(taskId);

        // TODO: test validations
    }
    
}
