/*
 * WAC关联Fit AP管理
 * WAC关联Fit AP第三方接口，主要特性：  · 根据指定的WAC设备ID查询关联的Fit AP列表 · 根据指定的WAC设备关联Fit AP列表 · 根据指定的WAC设备解除关联的Fit AP列表 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.huawei.cloudcampus.api.service;

import com.huawei.cloudcampus.api.ApiException;
import java.util.UUID;
import com.huawei.cloudcampus.api.model.WACFitApDto;
import com.huawei.cloudcampus.api.model.WACFitApResponseDto;
import com.huawei.cloudcampus.api.model.WACFitQueryResponseDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WACFitNorthboundApi
 */
@Ignore
public class WACFitNorthboundApiTest {

    private final WACFitNorthboundApi api = new WACFitNorthboundApi();

    
    /**
     * 关联指定的WAC设备和Fit AP列表
     *
     * ## 典型场景 ##    提供指定的WAC关联Fit AP的接口。 ## 接口功能 ##    提供指定的WAC关联Fit AP的接口。 ## 接口约束 ##    无。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addFitApsTest() throws ApiException {
        UUID acId = null;
        WACFitApDto body = null;
        WACFitApResponseDto response = api.addFitAps(acId, body);

        // TODO: test validations
    }
    
    /**
     * 解除关联指定的WAC设备和Fit AP列表
     *
     * ## 典型场景 ##    提供指定的WAC解除关联的Fit AP的接口。 ## 接口功能 ##    提供指定的WAC解除关联的Fit AP的接口。 ## 接口约束 ##    无。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFitApsTest() throws ApiException {
        UUID acId = null;
        WACFitApDto body = null;
        WACFitApResponseDto response = api.deleteFitAps(acId, body);

        // TODO: test validations
    }
    
    /**
     * 查询指定的WAC设备下关联的Fit AP列表
     *
     * ## 典型场景 ##    提供查询指定WAC设备下关联的Fit AP列表的接口。 ## 接口功能 ##    根据指定的WAC设备的ID查询关联的Fit AP列表。 ## 接口约束 ##    无。 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFitApsTest() throws ApiException {
        UUID acId = null;
        Integer pageSize = null;
        Integer pageIndex = null;
        WACFitQueryResponseDto response = api.getFitAps(acId, pageSize, pageIndex);

        // TODO: test validations
    }
    
}
